{{- if and .Values.openshift.enabled .Values.openshift.anyuidScc.createRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tasklattice.componentName" (dict "root" . "component" "anyuid") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tasklattice.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: {{ include "tasklattice.runtimeServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: {{ include "tasklattice.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  {{- if .Values.openshell.enabled }}
  - kind: ServiceAccount
    name: {{ include "openshell.serviceAccountName" .Subcharts.openshell }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
