apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: tasklattice-sandbox-policies
    namespace: tasklattice-sandboxes
    files:
      - catalog.yaml=policy-catalog.yaml
