apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Service
      name: tasklattice-litellm
    patch: |-
      - op: add
        path: /spec/type
        value: LoadBalancer
  - target:
      kind: Deployment
      name: tasklattice-litellm
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: UI_USERNAME
          valueFrom:
            secretKeyRef:
              name: tasklattice-litellm
              key: ui-username
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: UI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tasklattice-litellm
              key: ui-password
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LITELLM_SALT_KEY
          valueFrom:
            secretKeyRef:
              name: tasklattice-litellm
              key: salt-key
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DOCS_URL
          value: /docs
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ROOT_REDIRECT_URL
          value: /ui
