CREATE TABLE tasklattice.audit_logs (
  project_id TEXT NOT NULL,
  id TEXT NOT NULL,
  occurred_at TIMESTAMPTZ(6) NOT NULL,
  actor_type TEXT NOT NULL,
  actor_id TEXT NOT NULL,
  actor_name TEXT NOT NULL,
  actor_email TEXT,
  authorization_role TEXT NOT NULL,
  authorization_decision TEXT NOT NULL,
  action TEXT NOT NULL,
  verb TEXT NOT NULL,
  object_type TEXT NOT NULL,
  object_id TEXT NOT NULL,
  object_name TEXT NOT NULL,
  outcome TEXT NOT NULL,
  summary TEXT NOT NULL,
  request_id TEXT NOT NULL,
  http_method TEXT NOT NULL,
  route TEXT NOT NULL,
  ip_address TEXT NOT NULL,
  user_agent TEXT NOT NULL,
  parameters JSONB,
  request_body JSONB,
  metadata JSONB,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (project_id, id),
  CONSTRAINT audit_logs_project_id_fkey
    FOREIGN KEY (project_id) REFERENCES tasklattice.projects(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT audit_logs_actor_type_check
    CHECK (actor_type IN ('user', 'service_account', 'system')),
  CONSTRAINT audit_logs_authorization_decision_check
    CHECK (authorization_decision IN ('allowed', 'denied')),
  CONSTRAINT audit_logs_outcome_check
    CHECK (outcome IN ('success', 'failed', 'denied'))
);

CREATE INDEX audit_logs_project_time_idx
  ON tasklattice.audit_logs(project_id, occurred_at DESC);
CREATE INDEX audit_logs_project_actor_time_idx
  ON tasklattice.audit_logs(project_id, actor_id, occurred_at DESC);
CREATE INDEX audit_logs_project_action_time_idx
  ON tasklattice.audit_logs(project_id, action, occurred_at DESC);

INSERT INTO tasklattice.audit_logs (
  project_id,
  id,
  occurred_at,
  actor_type,
  actor_id,
  actor_name,
  actor_email,
  authorization_role,
  authorization_decision,
  action,
  verb,
  object_type,
  object_id,
  object_name,
  outcome,
  summary,
  request_id,
  http_method,
  route,
  ip_address,
  user_agent,
  parameters,
  request_body,
  metadata
)
SELECT
  'individual',
  fixture.id,
  fixture.occurred_at,
  fixture.actor_type,
  fixture.actor_id,
  fixture.actor_name,
  fixture.actor_email,
  fixture.authorization_role,
  fixture.authorization_decision,
  fixture.action,
  fixture.verb,
  fixture.object_type,
  fixture.object_id,
  fixture.object_name,
  fixture.outcome,
  fixture.summary,
  fixture.request_id,
  fixture.http_method,
  fixture.route,
  fixture.ip_address,
  fixture.user_agent,
  fixture.parameters,
  fixture.request_body,
  fixture.metadata
FROM (
  VALUES
    (
      'audit-001',
      CURRENT_TIMESTAMP - INTERVAL '4 minutes',
      'user',
      'local-admin',
      'Local Administrator',
      'admin@tasklattice.local',
      'admin',
      'allowed',
      'instance.create',
      'created',
      'Instance',
      'research-assistant',
      'Research Assistant',
      'success',
      'Created Instance “Research Assistant” with the OpenClaw runtime.',
      'req_01JZ8GFA1W8Q6BRF5TF5V6M5TQ',
      'POST',
      '/api/v1/projects/individual/instances',
      '192.168.10.24',
      'Chrome 138 · macOS',
      '{"source":"console"}'::jsonb,
      '{"name":"Research Assistant","runtime":"openclaw","modelProfileId":"balanced-global","instructions":"[REDACTED]"}'::jsonb,
      '{"region":"cn-shanghai","schemaVersion":1}'::jsonb
    ),
    (
      'audit-002',
      CURRENT_TIMESTAMP - INTERVAL '32 minutes',
      'user',
      'maya-chen',
      'Maya Chen',
      'maya.chen@example.com',
      'admin',
      'allowed',
      'access_policy.update',
      'updated',
      'Access Policy',
      'production-guardrails',
      'Production Guardrails',
      'success',
      'Updated Access Policy “Production Guardrails” from revision 6 to 7.',
      'req_01JZ8F8P2BKRY8EFQCSJD18YDG',
      'PUT',
      '/api/v1/projects/individual/access-policies/production-guardrails',
      '10.28.4.16',
      'Chrome 138 · Windows',
      '{"policyId":"production-guardrails"}'::jsonb,
      '{"revision":7,"effect":"allow","principals":["virtual-employee:security-reviewer"],"conditions":{"environment":"production"}}'::jsonb,
      '{"previousRevision":6,"changeTicket":"SEC-2841"}'::jsonb
    ),
    (
      'audit-003',
      CURRENT_TIMESTAMP - INTERVAL '1 hour 18 minutes',
      'user',
      'local-admin',
      'Local Administrator',
      'admin@tasklattice.local',
      'admin',
      'allowed',
      'project_member.invite',
      'invited',
      'Project Member',
      'alex.kim@example.com',
      'alex.kim@example.com',
      'success',
      'Invited alex.kim@example.com to this Project as a user.',
      'req_01JZ8CQKMZE6R7NV8NGHZ0MGH4',
      'POST',
      '/api/v1/projects/individual/members/invitations',
      '192.168.10.24',
      'Chrome 138 · macOS',
      '{}'::jsonb,
      '{"email":"alex.kim@example.com","role":"user"}'::jsonb,
      '{"notification":"queued"}'::jsonb
    ),
    (
      'audit-004',
      CURRENT_TIMESTAMP - INTERVAL '3 hours 6 minutes',
      'service_account',
      'deployment-bot',
      'Deployment Bot',
      NULL,
      'automation',
      'allowed',
      'runtime_policy.update',
      'updated',
      'Runtime Policy',
      'restricted-egress',
      'Restricted Egress',
      'failed',
      'Runtime Policy update failed validation because two network rules overlapped.',
      'req_01JZ86X0EZ0X7BQ42RYCGQY79C',
      'PUT',
      '/api/v1/projects/individual/policies/restricted-egress',
      '10.42.0.17',
      'TaskLattice Deploy Bot/1.8',
      '{"dryRun":false}'::jsonb,
      '{"networkRules":[{"host":"*.internal.example","port":443},{"host":"api.internal.example","port":443}]}'::jsonb,
      '{"validationCode":"OVERLAPPING_NETWORK_RULES","pipeline":"policy-sync"}'::jsonb
    ),
    (
      'audit-005',
      CURRENT_TIMESTAMP - INTERVAL '5 hours 42 minutes',
      'user',
      'maya-chen',
      'Maya Chen',
      'maya.chen@example.com',
      'admin',
      'denied',
      'mcp_server.delete',
      'deleted',
      'MCP Server',
      'production-github',
      'Production GitHub',
      'denied',
      'Deletion of MCP Server “Production GitHub” was denied by a retention policy.',
      'req_01JZ7Y7W7BF3CJJK43F6Q4CEEW',
      'DELETE',
      '/api/v1/projects/individual/catalog/mcp-servers/production-github',
      '10.28.4.16',
      'Chrome 138 · Windows',
      '{"force":false}'::jsonb,
      NULL,
      '{"policy":"retain-active-integrations","activeBindings":3}'::jsonb
    ),
    (
      'audit-006',
      CURRENT_TIMESTAMP - INTERVAL '1 day 2 hours',
      'user',
      'local-admin',
      'Local Administrator',
      'admin@tasklattice.local',
      'admin',
      'allowed',
      'project_quota.update',
      'updated',
      'Project Quota',
      'individual',
      'Project quota',
      'success',
      'Updated Project monthly budget and token limits.',
      'req_01JZ5KQQYYM4PDS1QDTQG412HC',
      'PUT',
      '/api/v1/projects/individual/quota',
      '192.168.10.24',
      'Chrome 138 · macOS',
      '{}'::jsonb,
      '{"hardBudgetUsd":2500,"budgetDuration":"30d","tpmLimit":1200000}'::jsonb,
      '{"previousHardBudgetUsd":2000,"revision":4}'::jsonb
    ),
    (
      'audit-007',
      CURRENT_TIMESTAMP - INTERVAL '2 days 4 hours',
      'system',
      'policy-reconciler',
      'Policy Reconciler',
      NULL,
      'system',
      'allowed',
      'access_policy.reconcile',
      'reconciled',
      'Access Policy',
      'production-guardrails',
      'Production Guardrails',
      'success',
      'Reconciled Access Policy “Production Guardrails” with the enforcement gateway.',
      'req_01JZ33CF90S0KVKRDHKQBWQ3V7',
      'POST',
      '/internal/reconciliation/access-policies/production-guardrails',
      '10.42.1.8',
      'TaskLattice Policy Reconciler/0.2',
      '{"revision":6}'::jsonb,
      NULL,
      '{"durationMs":418,"gateway":"managed"}'::jsonb
    ),
    (
      'audit-008',
      CURRENT_TIMESTAMP - INTERVAL '6 days 3 hours',
      'user',
      'alex-kim',
      'Alex Kim',
      'alex.kim@example.com',
      'user',
      'allowed',
      'knowledge_source.read',
      'viewed',
      'Knowledge Source',
      'security-runbooks',
      'Security Runbooks',
      'success',
      'Viewed Knowledge Source “Security Runbooks”.',
      'req_01JYN10K26PGDVSK7SDS1CV9T0',
      'GET',
      '/api/v1/projects/individual/catalog',
      '172.16.8.44',
      'Safari 18 · macOS',
      '{"kind":"knowledge-source","id":"security-runbooks"}'::jsonb,
      NULL,
      '{"responseStatus":200}'::jsonb
    )
) AS fixture(
  id,
  occurred_at,
  actor_type,
  actor_id,
  actor_name,
  actor_email,
  authorization_role,
  authorization_decision,
  action,
  verb,
  object_type,
  object_id,
  object_name,
  outcome,
  summary,
  request_id,
  http_method,
  route,
  ip_address,
  user_agent,
  parameters,
  request_body,
  metadata
)
WHERE EXISTS (
  SELECT 1 FROM tasklattice.projects WHERE id = 'individual'
)
ON CONFLICT (project_id, id) DO NOTHING;
