{{- if .Values.resourceDefaults.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "tali.fullname" . }}-container-resources
  labels:
    {{- include "tali.labels" . | nindent 4 }}
  annotations:
    {{- include "tali.resourceAnnotations" (dict "root" . "wave" "prerequisites") | nindent 4 }}
spec:
  limits:
    - type: Container
      default:
        {{- toYaml .Values.resourceDefaults.default | nindent 8 }}
      defaultRequest:
        {{- toYaml .Values.resourceDefaults.defaultRequest | nindent 8 }}
{{- end }}
