/**
 * Project authorization primitives shared by the Control API and its clients.
 *
 * Capabilities answer only "what action may be attempted". Resource relation
 * and an approval policy are evaluated separately by the admission layer.
 */

export const projectCapabilities = [
  "CAP_PROJECT_VIEW",
  "CAP_PROJECT_CREATE",
  "CAP_PROJECT_SETTINGS_UPDATE",
  "CAP_PROJECT_DELETE",
  "CAP_PROJECT_MEMBER_VIEW",
  "CAP_PROJECT_MEMBER_INVITE",
  "CAP_PROJECT_MEMBER_ROLE_ASSIGN",
  "CAP_PROJECT_MEMBER_REMOVE",
  "CAP_PROJECT_ROLE_VIEW",
  "CAP_PROJECT_ROLE_CREATE",
  "CAP_PROJECT_ROLE_UPDATE",
  "CAP_PROJECT_ROLE_DELETE",
  "CAP_PROJECT_QUOTA_VIEW",
  "CAP_PROJECT_QUOTA_UPDATE",
  "CAP_PROJECT_QUOTA_RECONCILE",

  "CAP_AGENT_REGISTRATION_VIEW",
  "CAP_AGENT_REGISTRATION_CREATE",
  "CAP_AGENT_REGISTRATION_DISCOVER",
  "CAP_AGENT_REGISTRATION_UPDATE",
  "CAP_AGENT_REGISTRATION_DELETE",
  "CAP_AGENT_CONNECTION_VIEW",
  "CAP_AGENT_CONNECTION_GRANT",
  "CAP_AGENT_CONNECTION_UPDATE",
  "CAP_AGENT_CONNECTION_REVOKE",
  "CAP_AGENT_INSTANCE_VIEW",
  "CAP_AGENT_INSTANCE_CONFIG_VIEW",
  "CAP_AGENT_INSTANCE_CREATE",
  "CAP_AGENT_INSTANCE_UPDATE",
  "CAP_AGENT_INSTANCE_START",
  "CAP_AGENT_INSTANCE_STOP",
  "CAP_AGENT_INSTANCE_RESTART",
  "CAP_AGENT_INSTANCE_DELETE",
  "CAP_AGENT_INSTANCE_OWNER_TRANSFER",
  "CAP_AGENT_INSTANCE_LOG_VIEW",
  "CAP_AGENT_INSTANCE_INTERACT",
  "CAP_AGENT_INSTANCE_TERMINAL_EXEC",
  "CAP_AGENT_INSTANCE_SKILL_ASSIGN",
  "CAP_AGENT_INSTANCE_MCP_SERVER_ASSIGN",
  "CAP_AGENT_INSTANCE_KNOWLEDGE_SOURCE_ASSIGN",
  "CAP_AGENT_INSTANCE_ACCESS_POLICY_ASSIGN",
  "CAP_AGENT_INSTANCE_RUNTIME_POLICY_ASSIGN",
  "CAP_AGENT_INSTANCE_MODEL_ROUTING_ASSIGN",
  "CAP_AGENT_INSTANCE_SECRET_BIND",
  "CAP_AGENT_ASSIGNMENT_VIEW",
  "CAP_AGENT_ASSIGNMENT_ASSIGN",
  "CAP_AGENT_ASSIGNMENT_UNASSIGN",
  "CAP_AGENT_SESSION_CREATE",
  "CAP_AGENT_SESSION_VIEW",
  "CAP_AGENT_SESSION_CONTENT_VIEW",
  "CAP_AGENT_SESSION_MESSAGE_SEND",
  "CAP_AGENT_SESSION_DELETE",
  "CAP_AGENT_SESSION_EXPORT",
  "CAP_AGENT_SESSION_SHARE",

  "CAP_AGENT_MEMORY_CONFIG_VIEW",
  "CAP_AGENT_MEMORY_CONFIG_UPDATE",
  "CAP_AGENT_MEMORY_EMBEDDING_ASSIGN",
  "CAP_AGENT_MEMORY_ITEM_VIEW",
  "CAP_AGENT_MEMORY_CONTENT_VIEW",
  "CAP_AGENT_MEMORY_CONTENT_WRITE",
  "CAP_AGENT_MEMORY_CONTENT_DELETE",
  "CAP_AGENT_MEMORY_CONTENT_PURGE",
  "CAP_AGENT_MEMORY_RECALL_USE",
  "CAP_AGENT_MEMORY_SEARCH",
  "CAP_AGENT_MEMORY_SESSION_INDEX_MANAGE",
  "CAP_AGENT_MEMORY_INDEX_STATUS_VIEW",
  "CAP_AGENT_MEMORY_INDEX_VALIDATE",
  "CAP_AGENT_MEMORY_INDEX_REBUILD",
  "CAP_AGENT_MEMORY_INDEX_PURGE",
  "CAP_AGENT_MEMORY_IMPORT",
  "CAP_AGENT_MEMORY_EXPORT",
  "CAP_AGENT_MEMORY_RETENTION_VIEW",
  "CAP_AGENT_MEMORY_RETENTION_UPDATE",
  "CAP_AGENT_MEMORY_LEGAL_HOLD_MANAGE",

  "CAP_SKILL_VIEW",
  "CAP_SKILL_CREATE",
  "CAP_SKILL_UPDATE",
  "CAP_SKILL_VERIFY",
  "CAP_SKILL_PUBLISH",
  "CAP_SKILL_SUSPEND",
  "CAP_SKILL_DELETE",
  "CAP_SKILL_ARTIFACT_METADATA_VIEW",
  "CAP_SKILL_ARTIFACT_DOWNLOAD",
  "CAP_SKILL_ARTIFACT_PUBLISH",
  "CAP_MCP_SERVER_VIEW",
  "CAP_MCP_SERVER_CREATE",
  "CAP_MCP_SERVER_UPDATE",
  "CAP_MCP_SERVER_DELETE",
  "CAP_MCP_SERVER_DISCOVER",
  "CAP_MCP_SERVER_TEST",
  "CAP_MCP_TOOL_VIEW",
  "CAP_MCP_TOOL_TEST_INVOKE",
  "CAP_KNOWLEDGE_SOURCE_VIEW",
  "CAP_KNOWLEDGE_SOURCE_CONTENT_VIEW",
  "CAP_KNOWLEDGE_SOURCE_CREATE",
  "CAP_KNOWLEDGE_SOURCE_UPDATE",
  "CAP_KNOWLEDGE_SOURCE_DELETE",
  "CAP_KNOWLEDGE_SOURCE_SYNC",
  "CAP_KNOWLEDGE_SOURCE_REINDEX",
  "CAP_AGENT_SPECIALIZATION_VIEW",
  "CAP_AGENT_SPECIALIZATION_CREATE",
  "CAP_AGENT_SPECIALIZATION_UPDATE",
  "CAP_AGENT_SPECIALIZATION_DELETE",
  "CAP_ACCESS_POLICY_VIEW",
  "CAP_ACCESS_POLICY_VERSION_VIEW",
  "CAP_ACCESS_POLICY_CREATE",
  "CAP_ACCESS_POLICY_UPDATE",
  "CAP_ACCESS_POLICY_DELETE",
  "CAP_RUNTIME_POLICY_VIEW",
  "CAP_RUNTIME_POLICY_CREATE",
  "CAP_RUNTIME_POLICY_UPDATE",
  "CAP_RUNTIME_POLICY_DELETE",
  "CAP_RUNTIME_POLICY_VALIDATE",
  "CAP_PROVIDER_VIEW",
  "CAP_PROVIDER_CREATE",
  "CAP_PROVIDER_UPDATE",
  "CAP_PROVIDER_DELETE",
  "CAP_PROVIDER_DISCOVER",
  "CAP_PROVIDER_VALIDATE",
  "CAP_PROVIDER_CREDENTIAL_ROTATE",
  "CAP_MODEL_VIEW",
  "CAP_MODEL_CREATE",
  "CAP_MODEL_UPDATE",
  "CAP_MODEL_DELETE",
  "CAP_MODEL_VALIDATE",
  "CAP_INFERENCE_GATEWAY_VIEW",
  "CAP_INFERENCE_GATEWAY_CREATE",
  "CAP_INFERENCE_GATEWAY_UPDATE",
  "CAP_INFERENCE_GATEWAY_DELETE",
  "CAP_INFERENCE_GATEWAY_VALIDATE",
  "CAP_MODEL_ROUTING_VIEW",
  "CAP_MODEL_ROUTING_CREATE",
  "CAP_MODEL_ROUTING_UPDATE",
  "CAP_MODEL_ROUTING_DELETE",
  "CAP_MODEL_ROUTING_VALIDATE",
  "CAP_MODEL_ROUTING_RECONCILE",
  "CAP_SECRET_METADATA_VIEW",
  "CAP_SECRET_CREATE",
  "CAP_SECRET_ROTATE",
  "CAP_SECRET_BIND",
  "CAP_SECRET_UNBIND",
  "CAP_SECRET_DELETE",

  "CAP_APPROVAL_REQUEST_VIEW",
  "CAP_APPROVAL_REQUEST_DRAFT_CREATE",
  "CAP_APPROVAL_REQUEST_DRAFT_UPDATE",
  "CAP_APPROVAL_REQUEST_SUBMIT",
  "CAP_APPROVAL_REQUEST_COMMENT",
  "CAP_APPROVAL_REQUEST_CANCEL",
  "CAP_APPROVAL_REQUEST_DECIDE",
  "CAP_APPROVAL_REQUEST_ASSIGN",
  "CAP_APPROVAL_POLICY_VIEW",
  "CAP_APPROVAL_POLICY_UPDATE",
  "CAP_APPROVED_CHANGE_APPLY",
  "CAP_APPROVAL_OVERRIDE",
  "CAP_AUDIT_VIEW",
  "CAP_AUDIT_DETAIL_VIEW",
  "CAP_AUDIT_SENSITIVE_CONTENT_VIEW",
  "CAP_AUDIT_EXPORT",
  "CAP_AUDIT_INTEGRITY_VERIFY",
  "CAP_AUDIT_RETENTION_UPDATE",
  "CAP_AUDIT_LEGAL_HOLD_MANAGE",
  "CAP_TRACE_VIEW",
  "CAP_TRACE_CONTENT_VIEW",
  "CAP_TRACE_EXPORT",
  "CAP_RUNTIME_LOG_VIEW",
  "CAP_RUNTIME_LOG_DOWNLOAD",
  "CAP_RUNTIME_OPERATION_VIEW",
  "CAP_RUNTIME_OPERATION_RECONCILE",
  "CAP_RUNTIME_OPERATION_CANCEL",
  "CAP_RUNTIME_OPERATION_ROLLBACK",
  "CAP_COST_VIEW",
  "CAP_COST_EXPORT",
  "CAP_USAGE_VIEW",
  "CAP_USAGE_EXPORT",
  "CAP_USAGE_DATA_QUALITY_VIEW",
] as const;

export type ProjectCapability = (typeof projectCapabilities)[number];

export const builtinProjectRoleIds = [
  "ROLE_PROJECT_ADMIN",
  "ROLE_AUDITOR",
  "ROLE_AGENT_DEVELOPER",
  "ROLE_USER",
  "ROLE_APPROVER",
] as const;

export type BuiltinProjectRoleId = (typeof builtinProjectRoleIds)[number];

export const projectMembershipRoles = [
  "admin",
  "auditor",
  "developer",
  "user",
  "approver",
] as const;

export type ProjectMembershipRole = (typeof projectMembershipRoles)[number];

export const assignableProjectMembershipRoles = [
  "admin",
  "auditor",
  "developer",
  "user",
  "approver",
] as const satisfies readonly ProjectMembershipRole[];

export type AssignableProjectMembershipRole =
  (typeof assignableProjectMembershipRoles)[number];

export const resourceRelations = [
  "OWNER",
  "MAINTAINER",
  "ASSIGNED",
  "SESSION_PARTICIPANT",
  "PROJECT_ANY",
] as const;

export type ResourceRelation = (typeof resourceRelations)[number];

export const authorizationDecisions = [
  "ALLOW",
  "DENY",
  "APPROVAL_REQUIRED",
] as const;

export type AuthorizationDecision = (typeof authorizationDecisions)[number];

export interface ProjectCapabilityDefinition {
  id: ProjectCapability;
  sideEffect: boolean;
  sensitiveContent: boolean;
}

const readOnlySuffixes = [
  "_VIEW",
  "_METADATA_VIEW",
  "_STATUS_VIEW",
  "_VERSION_VIEW",
  "_RETENTION_VIEW",
] as const;

const sensitiveCapabilities = new Set<ProjectCapability>([
  "CAP_AGENT_INSTANCE_TERMINAL_EXEC",
  "CAP_AGENT_SESSION_CONTENT_VIEW",
  "CAP_AGENT_SESSION_EXPORT",
  "CAP_AGENT_MEMORY_CONTENT_VIEW",
  "CAP_AGENT_MEMORY_CONTENT_WRITE",
  "CAP_AGENT_MEMORY_CONTENT_DELETE",
  "CAP_AGENT_MEMORY_CONTENT_PURGE",
  "CAP_AGENT_MEMORY_SEARCH",
  "CAP_AGENT_MEMORY_IMPORT",
  "CAP_AGENT_MEMORY_EXPORT",
  "CAP_KNOWLEDGE_SOURCE_CONTENT_VIEW",
  "CAP_AUDIT_SENSITIVE_CONTENT_VIEW",
  "CAP_AUDIT_EXPORT",
  "CAP_TRACE_CONTENT_VIEW",
  "CAP_TRACE_EXPORT",
  "CAP_RUNTIME_LOG_DOWNLOAD",
]);

export const projectCapabilityCatalog: readonly ProjectCapabilityDefinition[] =
  Object.freeze(projectCapabilities.map((id) => Object.freeze({
    id,
    sideEffect: !readOnlySuffixes.some((suffix) => id.endsWith(suffix)),
    sensitiveContent: sensitiveCapabilities.has(id),
  })));

const capabilityDefinitionById = new Map(
  projectCapabilityCatalog.map((definition) => [definition.id, definition]),
);

export function projectCapabilityDefinition(
  id: ProjectCapability,
): ProjectCapabilityDefinition {
  return capabilityDefinitionById.get(id)!;
}

export function isProjectCapability(value: string): value is ProjectCapability {
  return capabilityDefinitionById.has(value as ProjectCapability);
}
