/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectIdIndexRouteImport } from './routes/$projectId/index'
import { Route as ProjectIdCostRouteImport } from './routes/$projectId/cost'
import { Route as ProjectIdKnowledgeBaseRouteImport } from './routes/$projectId/knowledge-base'
import { Route as ProjectIdMcpServersRouteImport } from './routes/$projectId/mcp-servers'
import { Route as ProjectIdProfileRouteImport } from './routes/$projectId/profile'
import { Route as ProjectIdRuntimeRouteImport } from './routes/$projectId/runtime'
import { Route as ProjectIdRuntimePoliciesRouteImport } from './routes/$projectId/runtime-policies'
import { Route as ProjectIdSkillsRouteImport } from './routes/$projectId/skills'
import { Route as ProjectIdTracesRouteImport } from './routes/$projectId/traces'
import { Route as AuthSsoCompleteRouteImport } from './routes/auth/sso-complete'
import { Route as ProjectIdAccessPoliciesIndexRouteImport } from './routes/$projectId/access-policies/index'
import { Route as ProjectIdAccessPoliciesPolicyIdRouteImport } from './routes/$projectId/access-policies/$policyId'
import { Route as ProjectIdAgentGardenIndexRouteImport } from './routes/$projectId/agent-garden/index'
import { Route as ProjectIdAgentGardenAgentIdRouteImport } from './routes/$projectId/agent-garden/$agentId'
import { Route as ProjectIdAuditLogsIndexRouteImport } from './routes/$projectId/audit-logs/index'
import { Route as ProjectIdInstancesIndexRouteImport } from './routes/$projectId/instances/index'
import { Route as ProjectIdInstancesInstanceIdRouteImport } from './routes/$projectId/instances/$instanceId'
import { Route as ProjectIdRequestsIndexRouteImport } from './routes/$projectId/requests/index'
import { Route as ProjectIdRequestsNewRouteImport } from './routes/$projectId/requests/new'
import { Route as ProjectIdSettingIndexRouteImport } from './routes/$projectId/setting/index'
import { Route as ProjectIdSettingModelProfilesProfileIdRouteImport } from './routes/$projectId/setting/model-profiles/$profileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdIndexRoute = ProjectIdIndexRouteImport.update({
  id: '/$projectId/',
  path: '/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdCostRoute = ProjectIdCostRouteImport.update({
  id: '/$projectId/cost',
  path: '/$projectId/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdKnowledgeBaseRoute = ProjectIdKnowledgeBaseRouteImport.update({
  id: '/$projectId/knowledge-base',
  path: '/$projectId/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdMcpServersRoute = ProjectIdMcpServersRouteImport.update({
  id: '/$projectId/mcp-servers',
  path: '/$projectId/mcp-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdProfileRoute = ProjectIdProfileRouteImport.update({
  id: '/$projectId/profile',
  path: '/$projectId/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRuntimeRoute = ProjectIdRuntimeRouteImport.update({
  id: '/$projectId/runtime',
  path: '/$projectId/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRuntimePoliciesRoute =
  ProjectIdRuntimePoliciesRouteImport.update({
    id: '/$projectId/runtime-policies',
    path: '/$projectId/runtime-policies',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdSkillsRoute = ProjectIdSkillsRouteImport.update({
  id: '/$projectId/skills',
  path: '/$projectId/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdTracesRoute = ProjectIdTracesRouteImport.update({
  id: '/$projectId/traces',
  path: '/$projectId/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSsoCompleteRoute = AuthSsoCompleteRouteImport.update({
  id: '/auth/sso-complete',
  path: '/auth/sso-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdAccessPoliciesIndexRoute =
  ProjectIdAccessPoliciesIndexRouteImport.update({
    id: '/$projectId/access-policies/',
    path: '/$projectId/access-policies/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdAccessPoliciesPolicyIdRoute =
  ProjectIdAccessPoliciesPolicyIdRouteImport.update({
    id: '/$projectId/access-policies/$policyId',
    path: '/$projectId/access-policies/$policyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdAgentGardenIndexRoute =
  ProjectIdAgentGardenIndexRouteImport.update({
    id: '/$projectId/agent-garden/',
    path: '/$projectId/agent-garden/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdAgentGardenAgentIdRoute =
  ProjectIdAgentGardenAgentIdRouteImport.update({
    id: '/$projectId/agent-garden/$agentId',
    path: '/$projectId/agent-garden/$agentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdAuditLogsIndexRoute = ProjectIdAuditLogsIndexRouteImport.update({
  id: '/$projectId/audit-logs/',
  path: '/$projectId/audit-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdInstancesIndexRoute = ProjectIdInstancesIndexRouteImport.update({
  id: '/$projectId/instances/',
  path: '/$projectId/instances/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdInstancesInstanceIdRoute =
  ProjectIdInstancesInstanceIdRouteImport.update({
    id: '/$projectId/instances/$instanceId',
    path: '/$projectId/instances/$instanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdRequestsIndexRoute = ProjectIdRequestsIndexRouteImport.update({
  id: '/$projectId/requests/',
  path: '/$projectId/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRequestsNewRoute = ProjectIdRequestsNewRouteImport.update({
  id: '/$projectId/requests/new',
  path: '/$projectId/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdSettingIndexRoute = ProjectIdSettingIndexRouteImport.update({
  id: '/$projectId/setting/',
  path: '/$projectId/setting/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdSettingModelProfilesProfileIdRoute =
  ProjectIdSettingModelProfilesProfileIdRouteImport.update({
    id: '/$projectId/setting/model-profiles/$profileId',
    path: '/$projectId/setting/model-profiles/$profileId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$projectId/cost': typeof ProjectIdCostRoute
  '/$projectId/knowledge-base': typeof ProjectIdKnowledgeBaseRoute
  '/$projectId/mcp-servers': typeof ProjectIdMcpServersRoute
  '/$projectId/profile': typeof ProjectIdProfileRoute
  '/$projectId/runtime': typeof ProjectIdRuntimeRoute
  '/$projectId/runtime-policies': typeof ProjectIdRuntimePoliciesRoute
  '/$projectId/skills': typeof ProjectIdSkillsRoute
  '/$projectId/traces': typeof ProjectIdTracesRoute
  '/auth/sso-complete': typeof AuthSsoCompleteRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/access-policies/$policyId': typeof ProjectIdAccessPoliciesPolicyIdRoute
  '/$projectId/agent-garden/$agentId': typeof ProjectIdAgentGardenAgentIdRoute
  '/$projectId/instances/$instanceId': typeof ProjectIdInstancesInstanceIdRoute
  '/$projectId/requests/new': typeof ProjectIdRequestsNewRoute
  '/$projectId/access-policies/': typeof ProjectIdAccessPoliciesIndexRoute
  '/$projectId/agent-garden/': typeof ProjectIdAgentGardenIndexRoute
  '/$projectId/audit-logs/': typeof ProjectIdAuditLogsIndexRoute
  '/$projectId/instances/': typeof ProjectIdInstancesIndexRoute
  '/$projectId/requests/': typeof ProjectIdRequestsIndexRoute
  '/$projectId/setting/': typeof ProjectIdSettingIndexRoute
  '/$projectId/setting/model-profiles/$profileId': typeof ProjectIdSettingModelProfilesProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$projectId/cost': typeof ProjectIdCostRoute
  '/$projectId/knowledge-base': typeof ProjectIdKnowledgeBaseRoute
  '/$projectId/mcp-servers': typeof ProjectIdMcpServersRoute
  '/$projectId/profile': typeof ProjectIdProfileRoute
  '/$projectId/runtime': typeof ProjectIdRuntimeRoute
  '/$projectId/runtime-policies': typeof ProjectIdRuntimePoliciesRoute
  '/$projectId/skills': typeof ProjectIdSkillsRoute
  '/$projectId/traces': typeof ProjectIdTracesRoute
  '/auth/sso-complete': typeof AuthSsoCompleteRoute
  '/$projectId': typeof ProjectIdIndexRoute
  '/$projectId/access-policies/$policyId': typeof ProjectIdAccessPoliciesPolicyIdRoute
  '/$projectId/agent-garden/$agentId': typeof ProjectIdAgentGardenAgentIdRoute
  '/$projectId/instances/$instanceId': typeof ProjectIdInstancesInstanceIdRoute
  '/$projectId/requests/new': typeof ProjectIdRequestsNewRoute
  '/$projectId/access-policies': typeof ProjectIdAccessPoliciesIndexRoute
  '/$projectId/agent-garden': typeof ProjectIdAgentGardenIndexRoute
  '/$projectId/audit-logs': typeof ProjectIdAuditLogsIndexRoute
  '/$projectId/instances': typeof ProjectIdInstancesIndexRoute
  '/$projectId/requests': typeof ProjectIdRequestsIndexRoute
  '/$projectId/setting': typeof ProjectIdSettingIndexRoute
  '/$projectId/setting/model-profiles/$profileId': typeof ProjectIdSettingModelProfilesProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$projectId/cost': typeof ProjectIdCostRoute
  '/$projectId/knowledge-base': typeof ProjectIdKnowledgeBaseRoute
  '/$projectId/mcp-servers': typeof ProjectIdMcpServersRoute
  '/$projectId/profile': typeof ProjectIdProfileRoute
  '/$projectId/runtime': typeof ProjectIdRuntimeRoute
  '/$projectId/runtime-policies': typeof ProjectIdRuntimePoliciesRoute
  '/$projectId/skills': typeof ProjectIdSkillsRoute
  '/$projectId/traces': typeof ProjectIdTracesRoute
  '/auth/sso-complete': typeof AuthSsoCompleteRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/access-policies/$policyId': typeof ProjectIdAccessPoliciesPolicyIdRoute
  '/$projectId/agent-garden/$agentId': typeof ProjectIdAgentGardenAgentIdRoute
  '/$projectId/instances/$instanceId': typeof ProjectIdInstancesInstanceIdRoute
  '/$projectId/requests/new': typeof ProjectIdRequestsNewRoute
  '/$projectId/access-policies/': typeof ProjectIdAccessPoliciesIndexRoute
  '/$projectId/agent-garden/': typeof ProjectIdAgentGardenIndexRoute
  '/$projectId/audit-logs/': typeof ProjectIdAuditLogsIndexRoute
  '/$projectId/instances/': typeof ProjectIdInstancesIndexRoute
  '/$projectId/requests/': typeof ProjectIdRequestsIndexRoute
  '/$projectId/setting/': typeof ProjectIdSettingIndexRoute
  '/$projectId/setting/model-profiles/$profileId': typeof ProjectIdSettingModelProfilesProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$projectId/cost'
    | '/$projectId/knowledge-base'
    | '/$projectId/mcp-servers'
    | '/$projectId/profile'
    | '/$projectId/runtime'
    | '/$projectId/runtime-policies'
    | '/$projectId/skills'
    | '/$projectId/traces'
    | '/auth/sso-complete'
    | '/$projectId/'
    | '/$projectId/access-policies/$policyId'
    | '/$projectId/agent-garden/$agentId'
    | '/$projectId/instances/$instanceId'
    | '/$projectId/requests/new'
    | '/$projectId/access-policies/'
    | '/$projectId/agent-garden/'
    | '/$projectId/audit-logs/'
    | '/$projectId/instances/'
    | '/$projectId/requests/'
    | '/$projectId/setting/'
    | '/$projectId/setting/model-profiles/$profileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$projectId/cost'
    | '/$projectId/knowledge-base'
    | '/$projectId/mcp-servers'
    | '/$projectId/profile'
    | '/$projectId/runtime'
    | '/$projectId/runtime-policies'
    | '/$projectId/skills'
    | '/$projectId/traces'
    | '/auth/sso-complete'
    | '/$projectId'
    | '/$projectId/access-policies/$policyId'
    | '/$projectId/agent-garden/$agentId'
    | '/$projectId/instances/$instanceId'
    | '/$projectId/requests/new'
    | '/$projectId/access-policies'
    | '/$projectId/agent-garden'
    | '/$projectId/audit-logs'
    | '/$projectId/instances'
    | '/$projectId/requests'
    | '/$projectId/setting'
    | '/$projectId/setting/model-profiles/$profileId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/$projectId/cost'
    | '/$projectId/knowledge-base'
    | '/$projectId/mcp-servers'
    | '/$projectId/profile'
    | '/$projectId/runtime'
    | '/$projectId/runtime-policies'
    | '/$projectId/skills'
    | '/$projectId/traces'
    | '/auth/sso-complete'
    | '/$projectId/'
    | '/$projectId/access-policies/$policyId'
    | '/$projectId/agent-garden/$agentId'
    | '/$projectId/instances/$instanceId'
    | '/$projectId/requests/new'
    | '/$projectId/access-policies/'
    | '/$projectId/agent-garden/'
    | '/$projectId/audit-logs/'
    | '/$projectId/instances/'
    | '/$projectId/requests/'
    | '/$projectId/setting/'
    | '/$projectId/setting/model-profiles/$profileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProjectIdCostRoute: typeof ProjectIdCostRoute
  ProjectIdKnowledgeBaseRoute: typeof ProjectIdKnowledgeBaseRoute
  ProjectIdMcpServersRoute: typeof ProjectIdMcpServersRoute
  ProjectIdProfileRoute: typeof ProjectIdProfileRoute
  ProjectIdRuntimeRoute: typeof ProjectIdRuntimeRoute
  ProjectIdRuntimePoliciesRoute: typeof ProjectIdRuntimePoliciesRoute
  ProjectIdSkillsRoute: typeof ProjectIdSkillsRoute
  ProjectIdTracesRoute: typeof ProjectIdTracesRoute
  AuthSsoCompleteRoute: typeof AuthSsoCompleteRoute
  ProjectIdIndexRoute: typeof ProjectIdIndexRoute
  ProjectIdAccessPoliciesPolicyIdRoute: typeof ProjectIdAccessPoliciesPolicyIdRoute
  ProjectIdAgentGardenAgentIdRoute: typeof ProjectIdAgentGardenAgentIdRoute
  ProjectIdInstancesInstanceIdRoute: typeof ProjectIdInstancesInstanceIdRoute
  ProjectIdRequestsNewRoute: typeof ProjectIdRequestsNewRoute
  ProjectIdAccessPoliciesIndexRoute: typeof ProjectIdAccessPoliciesIndexRoute
  ProjectIdAgentGardenIndexRoute: typeof ProjectIdAgentGardenIndexRoute
  ProjectIdAuditLogsIndexRoute: typeof ProjectIdAuditLogsIndexRoute
  ProjectIdInstancesIndexRoute: typeof ProjectIdInstancesIndexRoute
  ProjectIdRequestsIndexRoute: typeof ProjectIdRequestsIndexRoute
  ProjectIdSettingIndexRoute: typeof ProjectIdSettingIndexRoute
  ProjectIdSettingModelProfilesProfileIdRoute: typeof ProjectIdSettingModelProfilesProfileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/': {
      id: '/$projectId/'
      path: '/$projectId'
      fullPath: '/$projectId/'
      preLoaderRoute: typeof ProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/cost': {
      id: '/$projectId/cost'
      path: '/$projectId/cost'
      fullPath: '/$projectId/cost'
      preLoaderRoute: typeof ProjectIdCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/knowledge-base': {
      id: '/$projectId/knowledge-base'
      path: '/$projectId/knowledge-base'
      fullPath: '/$projectId/knowledge-base'
      preLoaderRoute: typeof ProjectIdKnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/mcp-servers': {
      id: '/$projectId/mcp-servers'
      path: '/$projectId/mcp-servers'
      fullPath: '/$projectId/mcp-servers'
      preLoaderRoute: typeof ProjectIdMcpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/profile': {
      id: '/$projectId/profile'
      path: '/$projectId/profile'
      fullPath: '/$projectId/profile'
      preLoaderRoute: typeof ProjectIdProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/runtime': {
      id: '/$projectId/runtime'
      path: '/$projectId/runtime'
      fullPath: '/$projectId/runtime'
      preLoaderRoute: typeof ProjectIdRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/runtime-policies': {
      id: '/$projectId/runtime-policies'
      path: '/$projectId/runtime-policies'
      fullPath: '/$projectId/runtime-policies'
      preLoaderRoute: typeof ProjectIdRuntimePoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/skills': {
      id: '/$projectId/skills'
      path: '/$projectId/skills'
      fullPath: '/$projectId/skills'
      preLoaderRoute: typeof ProjectIdSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/traces': {
      id: '/$projectId/traces'
      path: '/$projectId/traces'
      fullPath: '/$projectId/traces'
      preLoaderRoute: typeof ProjectIdTracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sso-complete': {
      id: '/auth/sso-complete'
      path: '/auth/sso-complete'
      fullPath: '/auth/sso-complete'
      preLoaderRoute: typeof AuthSsoCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/access-policies/': {
      id: '/$projectId/access-policies/'
      path: '/$projectId/access-policies'
      fullPath: '/$projectId/access-policies/'
      preLoaderRoute: typeof ProjectIdAccessPoliciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/access-policies/$policyId': {
      id: '/$projectId/access-policies/$policyId'
      path: '/$projectId/access-policies/$policyId'
      fullPath: '/$projectId/access-policies/$policyId'
      preLoaderRoute: typeof ProjectIdAccessPoliciesPolicyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/agent-garden/': {
      id: '/$projectId/agent-garden/'
      path: '/$projectId/agent-garden'
      fullPath: '/$projectId/agent-garden/'
      preLoaderRoute: typeof ProjectIdAgentGardenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/agent-garden/$agentId': {
      id: '/$projectId/agent-garden/$agentId'
      path: '/$projectId/agent-garden/$agentId'
      fullPath: '/$projectId/agent-garden/$agentId'
      preLoaderRoute: typeof ProjectIdAgentGardenAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/audit-logs/': {
      id: '/$projectId/audit-logs/'
      path: '/$projectId/audit-logs'
      fullPath: '/$projectId/audit-logs/'
      preLoaderRoute: typeof ProjectIdAuditLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/instances/': {
      id: '/$projectId/instances/'
      path: '/$projectId/instances'
      fullPath: '/$projectId/instances/'
      preLoaderRoute: typeof ProjectIdInstancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/instances/$instanceId': {
      id: '/$projectId/instances/$instanceId'
      path: '/$projectId/instances/$instanceId'
      fullPath: '/$projectId/instances/$instanceId'
      preLoaderRoute: typeof ProjectIdInstancesInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/requests/': {
      id: '/$projectId/requests/'
      path: '/$projectId/requests'
      fullPath: '/$projectId/requests/'
      preLoaderRoute: typeof ProjectIdRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/requests/new': {
      id: '/$projectId/requests/new'
      path: '/$projectId/requests/new'
      fullPath: '/$projectId/requests/new'
      preLoaderRoute: typeof ProjectIdRequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/setting/': {
      id: '/$projectId/setting/'
      path: '/$projectId/setting'
      fullPath: '/$projectId/setting/'
      preLoaderRoute: typeof ProjectIdSettingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/setting/model-profiles/$profileId': {
      id: '/$projectId/setting/model-profiles/$profileId'
      path: '/$projectId/setting/model-profiles/$profileId'
      fullPath: '/$projectId/setting/model-profiles/$profileId'
      preLoaderRoute: typeof ProjectIdSettingModelProfilesProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProjectIdCostRoute: ProjectIdCostRoute,
  ProjectIdKnowledgeBaseRoute: ProjectIdKnowledgeBaseRoute,
  ProjectIdMcpServersRoute: ProjectIdMcpServersRoute,
  ProjectIdProfileRoute: ProjectIdProfileRoute,
  ProjectIdRuntimeRoute: ProjectIdRuntimeRoute,
  ProjectIdRuntimePoliciesRoute: ProjectIdRuntimePoliciesRoute,
  ProjectIdSkillsRoute: ProjectIdSkillsRoute,
  ProjectIdTracesRoute: ProjectIdTracesRoute,
  AuthSsoCompleteRoute: AuthSsoCompleteRoute,
  ProjectIdIndexRoute: ProjectIdIndexRoute,
  ProjectIdAccessPoliciesPolicyIdRoute: ProjectIdAccessPoliciesPolicyIdRoute,
  ProjectIdAgentGardenAgentIdRoute: ProjectIdAgentGardenAgentIdRoute,
  ProjectIdInstancesInstanceIdRoute: ProjectIdInstancesInstanceIdRoute,
  ProjectIdRequestsNewRoute: ProjectIdRequestsNewRoute,
  ProjectIdAccessPoliciesIndexRoute: ProjectIdAccessPoliciesIndexRoute,
  ProjectIdAgentGardenIndexRoute: ProjectIdAgentGardenIndexRoute,
  ProjectIdAuditLogsIndexRoute: ProjectIdAuditLogsIndexRoute,
  ProjectIdInstancesIndexRoute: ProjectIdInstancesIndexRoute,
  ProjectIdRequestsIndexRoute: ProjectIdRequestsIndexRoute,
  ProjectIdSettingIndexRoute: ProjectIdSettingIndexRoute,
  ProjectIdSettingModelProfilesProfileIdRoute:
    ProjectIdSettingModelProfilesProfileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
