/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdIndexRouteImport } from './routes/$projectId/index'
import { Route as AuthSsoCompleteRouteImport } from './routes/auth/sso-complete'
import { Route as ProjectIdSkillsRouteImport } from './routes/$projectId/skills'
import { Route as ProjectIdRuntimePoliciesRouteImport } from './routes/$projectId/runtime-policies'
import { Route as ProjectIdRuntimeRouteImport } from './routes/$projectId/runtime'
import { Route as ProjectIdModelsRouteImport } from './routes/$projectId/models'
import { Route as ProjectIdMcpServersRouteImport } from './routes/$projectId/mcp-servers'
import { Route as ProjectIdKnowledgeBaseRouteImport } from './routes/$projectId/knowledge-base'
import { Route as ProjectIdCostRouteImport } from './routes/$projectId/cost'
import { Route as ProjectIdVirtualEmployeesIndexRouteImport } from './routes/$projectId/virtual-employees/index'
import { Route as ProjectIdSettingIndexRouteImport } from './routes/$projectId/setting/index'
import { Route as ProjectIdRequestsIndexRouteImport } from './routes/$projectId/requests/index'
import { Route as ProjectIdInstancesIndexRouteImport } from './routes/$projectId/instances/index'
import { Route as ProjectIdVirtualEmployeesEmployeeIdRouteImport } from './routes/$projectId/virtual-employees/$employeeId'
import { Route as ProjectIdRequestsNewRouteImport } from './routes/$projectId/requests/new'
import { Route as ProjectIdInstancesInstanceIdRouteImport } from './routes/$projectId/instances/$instanceId'
import { Route as ProjectIdSettingModelProfilesProfileIdRouteImport } from './routes/$projectId/setting/model-profiles/$profileId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdIndexRoute = ProjectIdIndexRouteImport.update({
  id: '/$projectId/',
  path: '/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSsoCompleteRoute = AuthSsoCompleteRouteImport.update({
  id: '/auth/sso-complete',
  path: '/auth/sso-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdSkillsRoute = ProjectIdSkillsRouteImport.update({
  id: '/$projectId/skills',
  path: '/$projectId/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRuntimePoliciesRoute =
  ProjectIdRuntimePoliciesRouteImport.update({
    id: '/$projectId/runtime-policies',
    path: '/$projectId/runtime-policies',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdRuntimeRoute = ProjectIdRuntimeRouteImport.update({
  id: '/$projectId/runtime',
  path: '/$projectId/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdModelsRoute = ProjectIdModelsRouteImport.update({
  id: '/$projectId/models',
  path: '/$projectId/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdMcpServersRoute = ProjectIdMcpServersRouteImport.update({
  id: '/$projectId/mcp-servers',
  path: '/$projectId/mcp-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdKnowledgeBaseRoute = ProjectIdKnowledgeBaseRouteImport.update({
  id: '/$projectId/knowledge-base',
  path: '/$projectId/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdCostRoute = ProjectIdCostRouteImport.update({
  id: '/$projectId/cost',
  path: '/$projectId/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdVirtualEmployeesIndexRoute =
  ProjectIdVirtualEmployeesIndexRouteImport.update({
    id: '/$projectId/virtual-employees/',
    path: '/$projectId/virtual-employees/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdSettingIndexRoute = ProjectIdSettingIndexRouteImport.update({
  id: '/$projectId/setting/',
  path: '/$projectId/setting/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRequestsIndexRoute = ProjectIdRequestsIndexRouteImport.update({
  id: '/$projectId/requests/',
  path: '/$projectId/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdInstancesIndexRoute = ProjectIdInstancesIndexRouteImport.update({
  id: '/$projectId/instances/',
  path: '/$projectId/instances/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdVirtualEmployeesEmployeeIdRoute =
  ProjectIdVirtualEmployeesEmployeeIdRouteImport.update({
    id: '/$projectId/virtual-employees/$employeeId',
    path: '/$projectId/virtual-employees/$employeeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdRequestsNewRoute = ProjectIdRequestsNewRouteImport.update({
  id: '/$projectId/requests/new',
  path: '/$projectId/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdInstancesInstanceIdRoute =
  ProjectIdInstancesInstanceIdRouteImport.update({
    id: '/$projectId/instances/$instanceId',
    path: '/$projectId/instances/$instanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdSettingModelProfilesProfileIdRoute =
  ProjectIdSettingModelProfilesProfileIdRouteImport.update({
    id: '/$projectId/setting/model-profiles/$profileId',
    path: '/$projectId/setting/model-profiles/$profileId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$projectId/cost': typeof ProjectIdCostRoute
  '/$projectId/knowledge-base': typeof ProjectIdKnowledgeBaseRoute
  '/$projectId/mcp-servers': typeof ProjectIdMcpServersRoute
  '/$projectId/models': typeof ProjectIdModelsRoute
  '/$projectId/runtime': typeof ProjectIdRuntimeRoute
  '/$projectId/runtime-policies': typeof ProjectIdRuntimePoliciesRoute
  '/$projectId/skills': typeof ProjectIdSkillsRoute
  '/auth/sso-complete': typeof AuthSsoCompleteRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/instances/$instanceId': typeof ProjectIdInstancesInstanceIdRoute
  '/$projectId/requests/new': typeof ProjectIdRequestsNewRoute
  '/$projectId/virtual-employees/$employeeId': typeof ProjectIdVirtualEmployeesEmployeeIdRoute
  '/$projectId/instances/': typeof ProjectIdInstancesIndexRoute
  '/$projectId/requests/': typeof ProjectIdRequestsIndexRoute
  '/$projectId/setting/': typeof ProjectIdSettingIndexRoute
  '/$projectId/virtual-employees/': typeof ProjectIdVirtualEmployeesIndexRoute
  '/$projectId/setting/model-profiles/$profileId': typeof ProjectIdSettingModelProfilesProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$projectId/cost': typeof ProjectIdCostRoute
  '/$projectId/knowledge-base': typeof ProjectIdKnowledgeBaseRoute
  '/$projectId/mcp-servers': typeof ProjectIdMcpServersRoute
  '/$projectId/models': typeof ProjectIdModelsRoute
  '/$projectId/runtime': typeof ProjectIdRuntimeRoute
  '/$projectId/runtime-policies': typeof ProjectIdRuntimePoliciesRoute
  '/$projectId/skills': typeof ProjectIdSkillsRoute
  '/auth/sso-complete': typeof AuthSsoCompleteRoute
  '/$projectId': typeof ProjectIdIndexRoute
  '/$projectId/instances/$instanceId': typeof ProjectIdInstancesInstanceIdRoute
  '/$projectId/requests/new': typeof ProjectIdRequestsNewRoute
  '/$projectId/virtual-employees/$employeeId': typeof ProjectIdVirtualEmployeesEmployeeIdRoute
  '/$projectId/instances': typeof ProjectIdInstancesIndexRoute
  '/$projectId/requests': typeof ProjectIdRequestsIndexRoute
  '/$projectId/setting': typeof ProjectIdSettingIndexRoute
  '/$projectId/virtual-employees': typeof ProjectIdVirtualEmployeesIndexRoute
  '/$projectId/setting/model-profiles/$profileId': typeof ProjectIdSettingModelProfilesProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$projectId/cost': typeof ProjectIdCostRoute
  '/$projectId/knowledge-base': typeof ProjectIdKnowledgeBaseRoute
  '/$projectId/mcp-servers': typeof ProjectIdMcpServersRoute
  '/$projectId/models': typeof ProjectIdModelsRoute
  '/$projectId/runtime': typeof ProjectIdRuntimeRoute
  '/$projectId/runtime-policies': typeof ProjectIdRuntimePoliciesRoute
  '/$projectId/skills': typeof ProjectIdSkillsRoute
  '/auth/sso-complete': typeof AuthSsoCompleteRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/instances/$instanceId': typeof ProjectIdInstancesInstanceIdRoute
  '/$projectId/requests/new': typeof ProjectIdRequestsNewRoute
  '/$projectId/virtual-employees/$employeeId': typeof ProjectIdVirtualEmployeesEmployeeIdRoute
  '/$projectId/instances/': typeof ProjectIdInstancesIndexRoute
  '/$projectId/requests/': typeof ProjectIdRequestsIndexRoute
  '/$projectId/setting/': typeof ProjectIdSettingIndexRoute
  '/$projectId/virtual-employees/': typeof ProjectIdVirtualEmployeesIndexRoute
  '/$projectId/setting/model-profiles/$profileId': typeof ProjectIdSettingModelProfilesProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$projectId/cost'
    | '/$projectId/knowledge-base'
    | '/$projectId/mcp-servers'
    | '/$projectId/models'
    | '/$projectId/runtime'
    | '/$projectId/runtime-policies'
    | '/$projectId/skills'
    | '/auth/sso-complete'
    | '/$projectId/'
    | '/$projectId/instances/$instanceId'
    | '/$projectId/requests/new'
    | '/$projectId/virtual-employees/$employeeId'
    | '/$projectId/instances/'
    | '/$projectId/requests/'
    | '/$projectId/setting/'
    | '/$projectId/virtual-employees/'
    | '/$projectId/setting/model-profiles/$profileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$projectId/cost'
    | '/$projectId/knowledge-base'
    | '/$projectId/mcp-servers'
    | '/$projectId/models'
    | '/$projectId/runtime'
    | '/$projectId/runtime-policies'
    | '/$projectId/skills'
    | '/auth/sso-complete'
    | '/$projectId'
    | '/$projectId/instances/$instanceId'
    | '/$projectId/requests/new'
    | '/$projectId/virtual-employees/$employeeId'
    | '/$projectId/instances'
    | '/$projectId/requests'
    | '/$projectId/setting'
    | '/$projectId/virtual-employees'
    | '/$projectId/setting/model-profiles/$profileId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/$projectId/cost'
    | '/$projectId/knowledge-base'
    | '/$projectId/mcp-servers'
    | '/$projectId/models'
    | '/$projectId/runtime'
    | '/$projectId/runtime-policies'
    | '/$projectId/skills'
    | '/auth/sso-complete'
    | '/$projectId/'
    | '/$projectId/instances/$instanceId'
    | '/$projectId/requests/new'
    | '/$projectId/virtual-employees/$employeeId'
    | '/$projectId/instances/'
    | '/$projectId/requests/'
    | '/$projectId/setting/'
    | '/$projectId/virtual-employees/'
    | '/$projectId/setting/model-profiles/$profileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProjectIdCostRoute: typeof ProjectIdCostRoute
  ProjectIdKnowledgeBaseRoute: typeof ProjectIdKnowledgeBaseRoute
  ProjectIdMcpServersRoute: typeof ProjectIdMcpServersRoute
  ProjectIdModelsRoute: typeof ProjectIdModelsRoute
  ProjectIdRuntimeRoute: typeof ProjectIdRuntimeRoute
  ProjectIdRuntimePoliciesRoute: typeof ProjectIdRuntimePoliciesRoute
  ProjectIdSkillsRoute: typeof ProjectIdSkillsRoute
  AuthSsoCompleteRoute: typeof AuthSsoCompleteRoute
  ProjectIdIndexRoute: typeof ProjectIdIndexRoute
  ProjectIdInstancesInstanceIdRoute: typeof ProjectIdInstancesInstanceIdRoute
  ProjectIdRequestsNewRoute: typeof ProjectIdRequestsNewRoute
  ProjectIdVirtualEmployeesEmployeeIdRoute: typeof ProjectIdVirtualEmployeesEmployeeIdRoute
  ProjectIdInstancesIndexRoute: typeof ProjectIdInstancesIndexRoute
  ProjectIdRequestsIndexRoute: typeof ProjectIdRequestsIndexRoute
  ProjectIdSettingIndexRoute: typeof ProjectIdSettingIndexRoute
  ProjectIdVirtualEmployeesIndexRoute: typeof ProjectIdVirtualEmployeesIndexRoute
  ProjectIdSettingModelProfilesProfileIdRoute: typeof ProjectIdSettingModelProfilesProfileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/': {
      id: '/$projectId/'
      path: '/$projectId'
      fullPath: '/$projectId/'
      preLoaderRoute: typeof ProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sso-complete': {
      id: '/auth/sso-complete'
      path: '/auth/sso-complete'
      fullPath: '/auth/sso-complete'
      preLoaderRoute: typeof AuthSsoCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/skills': {
      id: '/$projectId/skills'
      path: '/$projectId/skills'
      fullPath: '/$projectId/skills'
      preLoaderRoute: typeof ProjectIdSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/runtime-policies': {
      id: '/$projectId/runtime-policies'
      path: '/$projectId/runtime-policies'
      fullPath: '/$projectId/runtime-policies'
      preLoaderRoute: typeof ProjectIdRuntimePoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/runtime': {
      id: '/$projectId/runtime'
      path: '/$projectId/runtime'
      fullPath: '/$projectId/runtime'
      preLoaderRoute: typeof ProjectIdRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/models': {
      id: '/$projectId/models'
      path: '/$projectId/models'
      fullPath: '/$projectId/models'
      preLoaderRoute: typeof ProjectIdModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/mcp-servers': {
      id: '/$projectId/mcp-servers'
      path: '/$projectId/mcp-servers'
      fullPath: '/$projectId/mcp-servers'
      preLoaderRoute: typeof ProjectIdMcpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/knowledge-base': {
      id: '/$projectId/knowledge-base'
      path: '/$projectId/knowledge-base'
      fullPath: '/$projectId/knowledge-base'
      preLoaderRoute: typeof ProjectIdKnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/cost': {
      id: '/$projectId/cost'
      path: '/$projectId/cost'
      fullPath: '/$projectId/cost'
      preLoaderRoute: typeof ProjectIdCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/virtual-employees/': {
      id: '/$projectId/virtual-employees/'
      path: '/$projectId/virtual-employees'
      fullPath: '/$projectId/virtual-employees/'
      preLoaderRoute: typeof ProjectIdVirtualEmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/setting/': {
      id: '/$projectId/setting/'
      path: '/$projectId/setting'
      fullPath: '/$projectId/setting/'
      preLoaderRoute: typeof ProjectIdSettingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/requests/': {
      id: '/$projectId/requests/'
      path: '/$projectId/requests'
      fullPath: '/$projectId/requests/'
      preLoaderRoute: typeof ProjectIdRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/instances/': {
      id: '/$projectId/instances/'
      path: '/$projectId/instances'
      fullPath: '/$projectId/instances/'
      preLoaderRoute: typeof ProjectIdInstancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/virtual-employees/$employeeId': {
      id: '/$projectId/virtual-employees/$employeeId'
      path: '/$projectId/virtual-employees/$employeeId'
      fullPath: '/$projectId/virtual-employees/$employeeId'
      preLoaderRoute: typeof ProjectIdVirtualEmployeesEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/requests/new': {
      id: '/$projectId/requests/new'
      path: '/$projectId/requests/new'
      fullPath: '/$projectId/requests/new'
      preLoaderRoute: typeof ProjectIdRequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/instances/$instanceId': {
      id: '/$projectId/instances/$instanceId'
      path: '/$projectId/instances/$instanceId'
      fullPath: '/$projectId/instances/$instanceId'
      preLoaderRoute: typeof ProjectIdInstancesInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/setting/model-profiles/$profileId': {
      id: '/$projectId/setting/model-profiles/$profileId'
      path: '/$projectId/setting/model-profiles/$profileId'
      fullPath: '/$projectId/setting/model-profiles/$profileId'
      preLoaderRoute: typeof ProjectIdSettingModelProfilesProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProjectIdCostRoute: ProjectIdCostRoute,
  ProjectIdKnowledgeBaseRoute: ProjectIdKnowledgeBaseRoute,
  ProjectIdMcpServersRoute: ProjectIdMcpServersRoute,
  ProjectIdModelsRoute: ProjectIdModelsRoute,
  ProjectIdRuntimeRoute: ProjectIdRuntimeRoute,
  ProjectIdRuntimePoliciesRoute: ProjectIdRuntimePoliciesRoute,
  ProjectIdSkillsRoute: ProjectIdSkillsRoute,
  AuthSsoCompleteRoute: AuthSsoCompleteRoute,
  ProjectIdIndexRoute: ProjectIdIndexRoute,
  ProjectIdInstancesInstanceIdRoute: ProjectIdInstancesInstanceIdRoute,
  ProjectIdRequestsNewRoute: ProjectIdRequestsNewRoute,
  ProjectIdVirtualEmployeesEmployeeIdRoute:
    ProjectIdVirtualEmployeesEmployeeIdRoute,
  ProjectIdInstancesIndexRoute: ProjectIdInstancesIndexRoute,
  ProjectIdRequestsIndexRoute: ProjectIdRequestsIndexRoute,
  ProjectIdSettingIndexRoute: ProjectIdSettingIndexRoute,
  ProjectIdVirtualEmployeesIndexRoute: ProjectIdVirtualEmployeesIndexRoute,
  ProjectIdSettingModelProfilesProfileIdRoute:
    ProjectIdSettingModelProfilesProfileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
