/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SandboxesRouteImport } from './routes/sandboxes'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as InstancesRouteImport } from './routes/instances'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvidersIndexRouteImport } from './routes/providers/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as RequestsNewRouteImport } from './routes/requests/new'
import { Route as ProvidersCostRouteImport } from './routes/providers/cost'
import { Route as AuthSsoCompleteRouteImport } from './routes/auth/sso-complete'
import { Route as AgentsNewRouteImport } from './routes/agents/new'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'
import { Route as ExtensionsSkillRouteImport } from './routes/Extensions/skill'
import { Route as ProvidersInferenceGroupsIndexRouteImport } from './routes/providers/inference-groups/index'
import { Route as ProvidersInferenceGroupsGroupIdRouteImport } from './routes/providers/inference-groups/$groupId'
import { Route as AgentsInstaceNewRouteImport } from './routes/agents/instace/new'
import { Route as AgentSandboxesRuntimeRouteImport } from './routes/agent/sandboxes/runtime'
import { Route as AgentSandboxesPolicyRouteImport } from './routes/agent/sandboxes/policy'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxesRoute = SandboxesRouteImport.update({
  id: '/sandboxes',
  path: '/sandboxes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesRoute = InstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvidersRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersCostRoute = ProvidersCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => ProvidersRoute,
} as any)
const AuthSsoCompleteRoute = AuthSsoCompleteRouteImport.update({
  id: '/auth/sso-complete',
  path: '/auth/sso-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsSkillRoute = ExtensionsSkillRouteImport.update({
  id: '/Extensions/skill',
  path: '/Extensions/skill',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersInferenceGroupsIndexRoute =
  ProvidersInferenceGroupsIndexRouteImport.update({
    id: '/inference-groups/',
    path: '/inference-groups/',
    getParentRoute: () => ProvidersRoute,
  } as any)
const ProvidersInferenceGroupsGroupIdRoute =
  ProvidersInferenceGroupsGroupIdRouteImport.update({
    id: '/inference-groups/$groupId',
    path: '/inference-groups/$groupId',
    getParentRoute: () => ProvidersRoute,
  } as any)
const AgentsInstaceNewRoute = AgentsInstaceNewRouteImport.update({
  id: '/agents/instace/new',
  path: '/agents/instace/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSandboxesRuntimeRoute = AgentSandboxesRuntimeRouteImport.update({
  id: '/agent/sandboxes/runtime',
  path: '/agent/sandboxes/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSandboxesPolicyRoute = AgentSandboxesPolicyRouteImport.update({
  id: '/agent/sandboxes/policy',
  path: '/agent/sandboxes/policy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/instances': typeof InstancesRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/policy': typeof PolicyRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/sandboxes': typeof SandboxesRoute
  '/skills': typeof SkillsRoute
  '/tickets': typeof TicketsRoute
  '/Extensions/skill': typeof ExtensionsSkillRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/auth/sso-complete': typeof AuthSsoCompleteRoute
  '/providers/cost': typeof ProvidersCostRoute
  '/requests/new': typeof RequestsNewRoute
  '/agents/': typeof AgentsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/agent/sandboxes/policy': typeof AgentSandboxesPolicyRoute
  '/agent/sandboxes/runtime': typeof AgentSandboxesRuntimeRoute
  '/agents/instace/new': typeof AgentsInstaceNewRoute
  '/providers/inference-groups/$groupId': typeof ProvidersInferenceGroupsGroupIdRoute
  '/providers/inference-groups/': typeof ProvidersInferenceGroupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/instances': typeof InstancesRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/policy': typeof PolicyRoute
  '/sandboxes': typeof SandboxesRoute
  '/skills': typeof SkillsRoute
  '/tickets': typeof TicketsRoute
  '/Extensions/skill': typeof ExtensionsSkillRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/auth/sso-complete': typeof AuthSsoCompleteRoute
  '/providers/cost': typeof ProvidersCostRoute
  '/requests/new': typeof RequestsNewRoute
  '/agents': typeof AgentsIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/agent/sandboxes/policy': typeof AgentSandboxesPolicyRoute
  '/agent/sandboxes/runtime': typeof AgentSandboxesRuntimeRoute
  '/agents/instace/new': typeof AgentsInstaceNewRoute
  '/providers/inference-groups/$groupId': typeof ProvidersInferenceGroupsGroupIdRoute
  '/providers/inference-groups': typeof ProvidersInferenceGroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/instances': typeof InstancesRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/policy': typeof PolicyRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/sandboxes': typeof SandboxesRoute
  '/skills': typeof SkillsRoute
  '/tickets': typeof TicketsRoute
  '/Extensions/skill': typeof ExtensionsSkillRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/auth/sso-complete': typeof AuthSsoCompleteRoute
  '/providers/cost': typeof ProvidersCostRoute
  '/requests/new': typeof RequestsNewRoute
  '/agents/': typeof AgentsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/agent/sandboxes/policy': typeof AgentSandboxesPolicyRoute
  '/agent/sandboxes/runtime': typeof AgentSandboxesRuntimeRoute
  '/agents/instace/new': typeof AgentsInstaceNewRoute
  '/providers/inference-groups/$groupId': typeof ProvidersInferenceGroupsGroupIdRoute
  '/providers/inference-groups/': typeof ProvidersInferenceGroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/instances'
    | '/knowledge'
    | '/login'
    | '/mcp'
    | '/policy'
    | '/providers'
    | '/sandboxes'
    | '/skills'
    | '/tickets'
    | '/Extensions/skill'
    | '/agents/$agentId'
    | '/agents/new'
    | '/auth/sso-complete'
    | '/providers/cost'
    | '/requests/new'
    | '/agents/'
    | '/providers/'
    | '/agent/sandboxes/policy'
    | '/agent/sandboxes/runtime'
    | '/agents/instace/new'
    | '/providers/inference-groups/$groupId'
    | '/providers/inference-groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/instances'
    | '/knowledge'
    | '/login'
    | '/mcp'
    | '/policy'
    | '/sandboxes'
    | '/skills'
    | '/tickets'
    | '/Extensions/skill'
    | '/agents/$agentId'
    | '/agents/new'
    | '/auth/sso-complete'
    | '/providers/cost'
    | '/requests/new'
    | '/agents'
    | '/providers'
    | '/agent/sandboxes/policy'
    | '/agent/sandboxes/runtime'
    | '/agents/instace/new'
    | '/providers/inference-groups/$groupId'
    | '/providers/inference-groups'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/instances'
    | '/knowledge'
    | '/login'
    | '/mcp'
    | '/policy'
    | '/providers'
    | '/sandboxes'
    | '/skills'
    | '/tickets'
    | '/Extensions/skill'
    | '/agents/$agentId'
    | '/agents/new'
    | '/auth/sso-complete'
    | '/providers/cost'
    | '/requests/new'
    | '/agents/'
    | '/providers/'
    | '/agent/sandboxes/policy'
    | '/agent/sandboxes/runtime'
    | '/agents/instace/new'
    | '/providers/inference-groups/$groupId'
    | '/providers/inference-groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  InstancesRoute: typeof InstancesRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PolicyRoute: typeof PolicyRoute
  ProvidersRoute: typeof ProvidersRouteWithChildren
  SandboxesRoute: typeof SandboxesRoute
  SkillsRoute: typeof SkillsRoute
  TicketsRoute: typeof TicketsRoute
  ExtensionsSkillRoute: typeof ExtensionsSkillRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  AgentsNewRoute: typeof AgentsNewRoute
  AuthSsoCompleteRoute: typeof AuthSsoCompleteRoute
  RequestsNewRoute: typeof RequestsNewRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  AgentSandboxesPolicyRoute: typeof AgentSandboxesPolicyRoute
  AgentSandboxesRuntimeRoute: typeof AgentSandboxesRuntimeRoute
  AgentsInstaceNewRoute: typeof AgentsInstaceNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandboxes': {
      id: '/sandboxes'
      path: '/sandboxes'
      fullPath: '/sandboxes'
      preLoaderRoute: typeof SandboxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances': {
      id: '/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof InstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/cost': {
      id: '/providers/cost'
      path: '/cost'
      fullPath: '/providers/cost'
      preLoaderRoute: typeof ProvidersCostRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/auth/sso-complete': {
      id: '/auth/sso-complete'
      path: '/auth/sso-complete'
      fullPath: '/auth/sso-complete'
      preLoaderRoute: typeof AuthSsoCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Extensions/skill': {
      id: '/Extensions/skill'
      path: '/Extensions/skill'
      fullPath: '/Extensions/skill'
      preLoaderRoute: typeof ExtensionsSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/inference-groups/': {
      id: '/providers/inference-groups/'
      path: '/inference-groups'
      fullPath: '/providers/inference-groups/'
      preLoaderRoute: typeof ProvidersInferenceGroupsIndexRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/providers/inference-groups/$groupId': {
      id: '/providers/inference-groups/$groupId'
      path: '/inference-groups/$groupId'
      fullPath: '/providers/inference-groups/$groupId'
      preLoaderRoute: typeof ProvidersInferenceGroupsGroupIdRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/agents/instace/new': {
      id: '/agents/instace/new'
      path: '/agents/instace/new'
      fullPath: '/agents/instace/new'
      preLoaderRoute: typeof AgentsInstaceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/sandboxes/runtime': {
      id: '/agent/sandboxes/runtime'
      path: '/agent/sandboxes/runtime'
      fullPath: '/agent/sandboxes/runtime'
      preLoaderRoute: typeof AgentSandboxesRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/sandboxes/policy': {
      id: '/agent/sandboxes/policy'
      path: '/agent/sandboxes/policy'
      fullPath: '/agent/sandboxes/policy'
      preLoaderRoute: typeof AgentSandboxesPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProvidersRouteChildren {
  ProvidersCostRoute: typeof ProvidersCostRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
  ProvidersInferenceGroupsGroupIdRoute: typeof ProvidersInferenceGroupsGroupIdRoute
  ProvidersInferenceGroupsIndexRoute: typeof ProvidersInferenceGroupsIndexRoute
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersCostRoute: ProvidersCostRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
  ProvidersInferenceGroupsGroupIdRoute: ProvidersInferenceGroupsGroupIdRoute,
  ProvidersInferenceGroupsIndexRoute: ProvidersInferenceGroupsIndexRoute,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InstancesRoute: InstancesRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PolicyRoute: PolicyRoute,
  ProvidersRoute: ProvidersRouteWithChildren,
  SandboxesRoute: SandboxesRoute,
  SkillsRoute: SkillsRoute,
  TicketsRoute: TicketsRoute,
  ExtensionsSkillRoute: ExtensionsSkillRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  AgentsNewRoute: AgentsNewRoute,
  AuthSsoCompleteRoute: AuthSsoCompleteRoute,
  RequestsNewRoute: RequestsNewRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  AgentSandboxesPolicyRoute: AgentSandboxesPolicyRoute,
  AgentSandboxesRuntimeRoute: AgentSandboxesRuntimeRoute,
  AgentsInstaceNewRoute: AgentsInstaceNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
