import {
  createPlatformDepartmentSchema,
  platformPeopleQuerySchema,
  replaceExternalRoleBindingsSchema,
  updatePlatformInfrastructureSettingsSchema,
  updatePlatformEmailSettingsSchema,
  updatePlatformSecuritySettingsSchema,
  updatePlatformSettingsSchema,
  validatePlatformEmailSettingsSchema,
  validatePlatformInfrastructureSettingsSchema,
  validatePlatformSsoSettingsSchema,
} from "@tali/contracts";
import { defineContracts } from "./contract";
import { response, route } from "./helpers";
import { createProjectInputSchema, openObjectSchema, projectSummarySchema } from "./schemas";

export const platformContracts = defineContracts([
  route({
    method: "post",
    path: "/platform/infrastructure/validate",
    operationId: "validatePlatformInfrastructureSettings",
    summary: "Validate Platform runtime connections",
    description: "Probe the draft Control, Runner, LiteLLM, and Runtime Namespace configuration without saving it.",
    tags: ["Platform administration"],
    request: { body: validatePlatformInfrastructureSettingsSchema },
    responses: { 200: response("Infrastructure validation result", openObjectSchema) },
  }),
  route({
    method: "put",
    path: "/platform/infrastructure",
    operationId: "updatePlatformInfrastructureSettings",
    summary: "Update Platform runtime connections",
    description: "Save a recently validated database-owned runtime connection configuration.",
    tags: ["Platform administration"],
    request: { body: updatePlatformInfrastructureSettingsSchema },
    responses: { 200: response("Updated Platform infrastructure settings", openObjectSchema) },
  }),
  route({
    method: "get",
    path: "/platform/people",
    operationId: "listPlatformPeople",
    summary: "List onboarded people",
    description: "Search and page human identities by name, Department membership, or Project membership.",
    tags: ["Platform administration"],
    request: { query: platformPeopleQuerySchema },
    responses: { 200: response("Platform people page", openObjectSchema) },
  }),
  route({
    method: "put",
    path: "/platform/security/role-bindings",
    operationId: "replaceExternalRoleBindings",
    summary: "Replace Keycloak Group role bindings",
    description: "Replace the explicit Group-to-Platform, Department, and Project role mappings used during SSO sign-in.",
    tags: ["Platform administration"],
    request: { body: replaceExternalRoleBindingsSchema },
    responses: { 200: response("Updated external role bindings", openObjectSchema) },
  }),
  route({
    method: "get",
    path: "/platform/roles",
    operationId: "getBuiltinRoleCatalog",
    summary: "Read the built-in Role catalog",
    description: "Read all immutable Platform, Department, and Project Roles with their persisted Capability grants and resource relations.",
    tags: ["Platform administration"],
    responses: { 200: response("Built-in Role catalog", openObjectSchema) },
  }),
  route({
    method: "post",
    path: "/platform/email/validate",
    operationId: "validatePlatformEmailSettings",
    summary: "Validate a platform SMTP connection",
    description: "Test the draft SMTP connection and authentication without saving the configuration.",
    tags: ["Platform administration"],
    request: { body: validatePlatformEmailSettingsSchema },
    responses: { 200: response("SMTP validation result", openObjectSchema) },
  }),
  route({
    method: "put",
    path: "/platform/email",
    operationId: "updatePlatformEmailSettings",
    summary: "Update platform email delivery",
    description: "Save the database-owned SMTP delivery configuration and encrypted password.",
    tags: ["Platform administration"],
    request: { body: updatePlatformEmailSettingsSchema },
    responses: { 200: response("Updated Platform email settings", openObjectSchema) },
  }),
  route({
    method: "post",
    path: "/platform/security/validate",
    operationId: "validatePlatformSsoSettings",
    summary: "Validate Platform authentication settings",
    description: "Validate the complete Local and OIDC authentication draft without saving it.",
    tags: ["Platform administration"],
    request: { body: validatePlatformSsoSettingsSchema },
    responses: { 200: response("OIDC validation result", openObjectSchema) },
  }),
  route({
    method: "put",
    path: "/platform/security",
    operationId: "updatePlatformSecuritySettings",
    summary: "Update Platform authentication settings",
    description: "Save a recently validated database-owned Local and OIDC authentication configuration.",
    tags: ["Platform administration"],
    request: { body: updatePlatformSecuritySettingsSchema },
    responses: { 200: response("Updated Platform security settings", openObjectSchema) },
  }),
  route({
    method: "get",
    path: "/platform/settings",
    operationId: "getPlatformSettings",
    summary: "Read Platform Administrator settings",
    description: "Read platform-wide runtime and Provider admission settings.",
    tags: ["Platform administration"],
    responses: { 200: response("Platform settings", openObjectSchema) },
  }),
  route({
    method: "put",
    path: "/platform/settings",
    operationId: "updatePlatformSettings",
    summary: "Update Platform Administrator settings",
    description: "Update platform-wide runtime and Provider admission settings.",
    tags: ["Platform administration"],
    request: { body: updatePlatformSettingsSchema },
    responses: { 200: response("Updated Platform settings", openObjectSchema) },
  }),
  route({
    method: "get",
    path: "/platform/organization",
    operationId: "getPlatformOrganization",
    summary: "Read the platform organization",
    description: "List Departments, Projects, and people visible at the platform scope.",
    tags: ["Platform administration"],
    responses: { 200: response("Platform organization", openObjectSchema) },
  }),
  route({
    method: "post",
    path: "/platform/departments",
    operationId: "createPlatformDepartment",
    summary: "Create a Department at platform scope",
    description: "Create a Department and assign its initial Department Administrator.",
    tags: ["Platform administration"],
    request: { body: createPlatformDepartmentSchema },
    responses: { 201: response("Created Department", openObjectSchema) },
  }),
  route({
    method: "post",
    path: "/platform/projects",
    operationId: "createPlatformProject",
    summary: "Create a Project at platform scope",
    description: "Create a Project in a Department using Platform Administrator authority.",
    tags: ["Platform administration"],
    request: { body: createProjectInputSchema },
    responses: { 201: response("Created Project", projectSummarySchema) },
  }),
]);
