import type { ResourceCatalog } from "@tali/contracts";
import vendorSkillManifest from "../../../../artifacts/skills/vendor/manifest.json";
import { mcpServerTemplates } from "./mcp-server-templates";

const skillCatalogUpdatedAt = "2026-07-26T00:00:00.000Z";

function vendorArtifact(skillId: string, version: string) {
  const artifact = vendorSkillManifest.artifacts.find(
    (candidate) =>
      candidate.skillId === skillId && candidate.version === version,
  );
  if (!artifact) {
    throw new Error(`Vendor Skill artifact is missing: ${skillId}@${version}`);
  }
  return {
    digest: artifact.digest,
    endpoint: `tali+postgresql://skill-artifacts/${skillId}/${version}`,
  };
}

function skillInformation(
  author: string,
  problemStatement: string,
  useCases: string[],
  usageGuide: string,
) {
  return {
    author,
    problemStatement,
    updatedAt: skillCatalogUpdatedAt,
    useCases,
    usageGuide,
  };
}

export const developmentResourceCatalog: ResourceCatalog = {
  skills: [
    {
      id: "employee-policy-search",
      name: "Employee Policy Search",
      description: "Find and answer questions about company HR policies.",
      ...skillInformation(
        "People Operations",
        "Employees lose time searching across policy documents and may act on outdated or incomplete guidance.",
        ["Answer leave, benefits, and workplace policy questions", "Locate the approved policy behind an HR answer"],
        "Connect an approved HR knowledge source, then ask a specific policy question. The Skill returns an answer with the relevant policy context for review.",
      ),
      category: "HR",
      trustLevel: "TRUSTED_SOURCE",
      compatibleAgents: ["hermes", "openai"],
      version: "1.2.0",
      ...vendorArtifact("employee-policy-search", "1.2.0"),
      owner: "People Operations",
      permissions: 1,
      status: "PUBLISHED",
    },
    {
      id: "document-summarization",
      name: "Document Summarization",
      description: "Summarize HR documents and reports.",
      ...skillInformation(
        "TaskLattice Relay Knowledge",
        "Long internal documents are difficult to review quickly and important decisions can be hidden in supporting detail.",
        ["Create an executive summary of an internal document", "Extract decisions, risks, and follow-up actions from a report"],
        "Provide one or more approved documents and specify the audience and desired level of detail. Review cited source sections before sharing the summary.",
      ),
      category: "Knowledge",
      trustLevel: "BUILT_IN",
      compatibleAgents: ["hermes", "openai"],
      version: "2.0.1",
      ...vendorArtifact("document-summarization", "2.0.1"),
      owner: "Knowledge Team",
      permissions: 1,
      status: "PUBLISHED",
    },
    {
      id: "onboarding-guidance",
      name: "Onboarding Guidance",
      description: "Guide new hires through onboarding steps and resources.",
      ...skillInformation(
        "People Operations",
        "New hires receive fragmented onboarding instructions and managers repeat the same coordination work.",
        ["Guide a new hire through their first-week checklist", "Answer role-specific onboarding questions"],
        "Provide the employee role, location, and start date. Connect the approved onboarding knowledge source before requesting a personalized checklist.",
      ),
      category: "HR",
      trustLevel: "TRUSTED_SOURCE",
      compatibleAgents: ["hermes", "openclaw"],
      version: "1.1.0",
      ...vendorArtifact("onboarding-guidance", "1.1.0"),
      owner: "People Operations",
      permissions: 2,
      status: "PUBLISHED",
    },
    {
      id: "data-extraction",
      name: "Data Extraction",
      description: "Extract structured data from documents and forms.",
      ...skillInformation(
        "TaskLattice Relay Data",
        "Operational data arrives in inconsistent documents and forms that cannot be processed reliably by downstream systems.",
        ["Extract invoice or form fields into JSON", "Normalize repeated document fields for a workflow"],
        "Provide the source document and the expected field schema. Validate required fields and confidence-sensitive values before sending the result downstream.",
      ),
      category: "Data",
      trustLevel: "BUILT_IN",
      compatibleAgents: ["hermes", "openclaw", "openai"],
      version: "1.3.0",
      ...vendorArtifact("data-extraction", "1.3.0"),
      owner: "Data Platform",
      permissions: 2,
      status: "PUBLISHED",
    },
    {
      id: "citation-builder",
      name: "Citation Builder",
      description: "Create traceable citations for research findings.",
      ...skillInformation(
        "Knowledge Team",
        "Research claims are difficult to audit when evidence links and source context are assembled manually.",
        ["Add traceable evidence to a research brief", "Normalize source references collected by multiple Agents"],
        "Pass the research findings together with their source URLs or documents. The Skill produces normalized citations and flags claims without supporting evidence.",
      ),
      category: "Research",
      trustLevel: "TRUSTED_SOURCE",
      compatibleAgents: ["openai", "claude-code"],
      version: "1.5.0",
      ...vendorArtifact("citation-builder", "1.5.0"),
      owner: "Knowledge Team",
      permissions: 1,
      status: "PUBLISHED",
    },
    {
      id: "incident-triage",
      name: "Incident Triage",
      description: "Triage service alerts and assemble an evidence-backed incident summary.",
      ...skillInformation(
        "TaskLattice Relay Operations",
        "Responders spend critical time correlating alerts, logs, and recent changes before they can choose the next action.",
        ["Prepare the first incident briefing", "Correlate alerts with recent infrastructure changes"],
        "Connect read-only observability sources and provide the alert context. Use the generated summary as evidence for a responder, not as authorization to execute changes.",
      ),
      category: "Operations",
      trustLevel: "BUILT_IN",
      compatibleAgents: ["hermes", "openclaw", "claude-code"],
      version: "2.2.0",
      ...vendorArtifact("incident-triage", "2.2.0"),
      owner: "Platform Operations",
      permissions: 3,
      status: "PUBLISHED",
    },
    {
      id: "infrastructure-change-review",
      name: "Infrastructure Change Review",
      description: "Review infrastructure changes against operational safeguards.",
      ...skillInformation(
        "Platform Operations",
        "Infrastructure changes can bypass operational conventions or introduce risks that are difficult to spot during manual review.",
        ["Review a pull request containing infrastructure changes", "Check a deployment plan against platform safeguards"],
        "Provide the proposed diff and target environment. Connect the relevant policy source, then review every warning before approving the change.",
      ),
      category: "Operations",
      trustLevel: "TRUSTED_SOURCE",
      compatibleAgents: ["openclaw", "claude-code", "openai"],
      version: "1.8.0",
      ...vendorArtifact("infrastructure-change-review", "1.8.0"),
      owner: "Platform Operations",
      permissions: 4,
      status: "PUBLISHED",
    },
    {
      id: "customer-conversation-summary",
      name: "Customer Conversation Summary",
      description: "Summarize customer conversations and identify the requested outcome.",
      ...skillInformation(
        "TaskLattice Relay Customer Experience",
        "Support teams lose context when long conversations are handed between people or Agents.",
        ["Create a handoff summary for another support owner", "Extract the customer's goal, blockers, and promised actions"],
        "Provide the conversation transcript and optional account context. Confirm sensitive details are appropriate for the destination before sharing the summary.",
      ),
      category: "Customer Support",
      trustLevel: "BUILT_IN",
      compatibleAgents: ["hermes", "openai"],
      version: "1.4.0",
      ...vendorArtifact("customer-conversation-summary", "1.4.0"),
      owner: "Customer Experience",
      permissions: 2,
      status: "PUBLISHED",
    },
    {
      id: "knowledge-answering",
      name: "Knowledge Answering",
      description: "Answer product questions using approved support knowledge.",
      ...skillInformation(
        "Customer Experience",
        "Support answers become inconsistent when Agents rely on memory instead of the current approved knowledge base.",
        ["Answer a product usage question", "Explain an approved troubleshooting procedure"],
        "Attach an approved product knowledge source and ask a focused question. The Skill should be configured to cite the material used for the answer.",
      ),
      category: "Customer Support",
      trustLevel: "TRUSTED_SOURCE",
      compatibleAgents: ["hermes", "openclaw", "openai"],
      version: "2.3.0",
      ...vendorArtifact("knowledge-answering", "2.3.0"),
      owner: "Customer Experience",
      permissions: 1,
      status: "PUBLISHED",
    },
    {
      id: "skill-sql-query",
      name: "SQL Query",
      description: "Run governed read-only queries and return structured results.",
      ...skillInformation(
        "TaskLattice Relay Data",
        "Agents need structured business data but unrestricted SQL access creates correctness and security risks.",
        ["Answer a reporting question from an approved database", "Retrieve read-only records for another workflow step"],
        "Connect a read-only database identity, describe the required result, and review the generated query and row limits before execution.",
      ),
      category: "Data",
      trustLevel: "BUILT_IN",
      compatibleAgents: ["claude-code", "openai"],
      version: "1.4.2",
      ...vendorArtifact("skill-sql-query", "1.4.2"),
      owner: "Data Platform",
      permissions: 2,
      status: "PUBLISHED",
    },
    {
      id: "skill-code-generation",
      name: "Code Generation",
      description: "Generate and revise code inside an approved project boundary.",
      ...skillInformation(
        "Developer Experience",
        "Engineering tasks require repetitive code changes, but generated patches need explicit repository and execution boundaries.",
        ["Draft a scoped implementation from an issue", "Refactor code and produce a reviewable patch"],
        "Attach the Skill only to an isolated development Agent. Provide repository scope, acceptance criteria, and allowed commands; review the patch and tests before merging.",
      ),
      category: "Developer Tools",
      trustLevel: "UNSAFE",
      compatibleAgents: ["openclaw", "claude-code", "openai"],
      version: "0.9.0",
      ...vendorArtifact("skill-code-generation", "0.9.0"),
      owner: "Developer Experience",
      permissions: 4,
      status: "DRAFT",
    },
    {
      id: "skill-web-research",
      name: "Web Research",
      description: "Collect public sources and produce citation-backed research notes.",
      ...skillInformation(
        "Knowledge Team",
        "Open-web research is slow to reproduce and conclusions are easy to separate from their original sources.",
        ["Investigate a current technical topic", "Collect sources for a market or product comparison"],
        "State the research question, date sensitivity, and source constraints. Review source quality and publication dates before accepting the synthesized findings.",
      ),
      category: "Research",
      trustLevel: "TRUSTED_SOURCE",
      compatibleAgents: ["hermes", "openclaw", "openai"],
      version: "2.1.0",
      ...vendorArtifact("skill-web-research", "2.1.0"),
      owner: "Knowledge Team",
      permissions: 3,
      status: "PUBLISHED",
    },
    {
      id: "helm-chart-developer",
      name: "Helm Chart Developer",
      description: "Design, review, and troubleshoot Helm charts, templates, values, and release packaging.",
      ...skillInformation(
        "Platform Engineering",
        "Helm changes are difficult to validate across environments and template mistakes often appear only during deployment.",
        ["Create or update a Helm chart", "Diagnose rendering and values override problems"],
        "Provide the chart, target Kubernetes versions, and environment values. Render and lint the result before allowing any cluster deployment.",
      ),
      category: "Developer Tools",
      trustLevel: "TRUSTED_SOURCE",
      compatibleAgents: ["openclaw", "claude-code"],
      version: "1.0.0",
      ...vendorArtifact("helm-chart-developer", "1.0.0"),
      owner: "Platform Engineering",
      permissions: 3,
      status: "PUBLISHED",
    },
    {
      id: "kubernetes-expert",
      name: "Kubernetes Expert",
      description: "Diagnose Kubernetes workloads and author safe manifests, controllers, and operational changes.",
      ...skillInformation(
        "Platform Engineering",
        "Kubernetes failures require correlating manifests, runtime state, and platform constraints without granting unnecessary write access.",
        ["Diagnose a failing workload", "Draft a safe Kubernetes manifest or operational change"],
        "Start with read-only cluster context and the affected manifests. Require operator approval before applying generated changes to a cluster.",
      ),
      category: "Developer Tools",
      trustLevel: "TRUSTED_SOURCE",
      compatibleAgents: ["openclaw", "claude-code", "openai"],
      version: "1.0.0",
      ...vendorArtifact("kubernetes-expert", "1.0.0"),
      owner: "Platform Engineering",
      permissions: 4,
      status: "PUBLISHED",
    },
    {
      id: "ocp-expert",
      name: "OCP Expert",
      description: "Operate OpenShift clusters with expertise in Routes, Operators, SCCs, and platform-specific workflows.",
      ...skillInformation(
        "Platform Engineering",
        "OpenShift adds platform-specific security and lifecycle behavior that generic Kubernetes guidance can miss.",
        ["Troubleshoot Routes, Operators, or SCC behavior", "Review an OpenShift-specific deployment plan"],
        "Provide the cluster version, namespace, relevant resources, and read-only diagnostics. Escalate SCC or cluster-wide changes for explicit approval.",
      ),
      category: "Operations",
      trustLevel: "TRUSTED_SOURCE",
      compatibleAgents: ["hermes", "openclaw", "claude-code"],
      version: "1.0.0",
      ...vendorArtifact("ocp-expert", "1.0.0"),
      owner: "Platform Engineering",
      permissions: 4,
      status: "PUBLISHED",
    },
  ],
  mcpServers: [],
  mcpServerTemplates,
  knowledgeSources: [],
  specializations: [
    {
      id: "general-purpose",
      name: "General Purpose",
      roleLabel: "General Assistant",
      icon: "sparkles",
      description: "A flexible Agent that starts without preselected capabilities.",
      systemPrompt: "You are a focused internal assistant. Complete the user's request inside the OpenShell sandbox and explain the evidence clearly.",
      defaultSkillIds: [],
      defaultMcpServerIds: [],
      defaultKnowledgeSourceIds: [],
    },
    {
      id: "hr",
      name: "HR",
      roleLabel: "HR Specialist",
      icon: "users",
      description: "Provides support for HR policies, employee onboarding, benefits, and internal HR processes.",
      systemPrompt: "You are an HR support Agent. Answer employee questions using approved company policies and connected knowledge sources. Be clear about policy scope, protect confidential employee data, and escalate decisions that require a People Operations owner.",
      defaultSkillIds: ["employee-policy-search", "document-summarization", "onboarding-guidance"],
      defaultMcpServerIds: [],
      defaultKnowledgeSourceIds: [],
    },
    {
      id: "research-analyst",
      name: "Research Analyst",
      roleLabel: "Research Analyst",
      icon: "telescope",
      description: "Collects evidence, compares sources, and produces citation-backed research.",
      systemPrompt: "You are a research analyst. Investigate the request using approved sources, distinguish evidence from inference, cite material claims, surface uncertainty, and provide a concise decision-ready synthesis.",
      defaultSkillIds: ["skill-web-research", "citation-builder", "document-summarization"],
      defaultMcpServerIds: [],
      defaultKnowledgeSourceIds: [],
    },
    {
      id: "devops-engineer",
      name: "DevOps Engineer",
      roleLabel: "DevOps Engineer",
      icon: "settings",
      description: "Investigates operational issues and reviews infrastructure changes safely.",
      systemPrompt: "You are a DevOps engineering Agent. Diagnose from observable evidence, preserve production safety, explain operational risk, and propose reversible changes with explicit verification and rollback steps.",
      defaultSkillIds: ["incident-triage", "infrastructure-change-review", "helm-chart-developer", "kubernetes-expert", "ocp-expert"],
      defaultMcpServerIds: [],
      defaultKnowledgeSourceIds: [],
    },
    {
      id: "customer-support",
      name: "Customer Support",
      roleLabel: "Customer Support Specialist",
      icon: "headphones",
      description: "Resolves product questions using approved support knowledge and escalation paths.",
      systemPrompt: "You are a customer support Agent. Understand the customer's goal, use approved support knowledge, give precise next actions, avoid unsupported claims, and escalate account or product issues that require a human owner.",
      defaultSkillIds: ["customer-conversation-summary", "knowledge-answering"],
      defaultMcpServerIds: [],
      defaultKnowledgeSourceIds: [],
    },
    {
      id: "custom",
      name: "Custom",
      roleLabel: "Custom Agent",
      icon: "briefcase",
      description: "Define custom instructions and assemble capabilities from the available catalog.",
      systemPrompt: "",
      defaultSkillIds: [],
      defaultMcpServerIds: [],
      defaultKnowledgeSourceIds: [],
    },
  ],
};
