import type { ResourceCatalog } from "@tasklattice/contracts";
import { mcpServerTemplates } from "./mcp-server-templates";

export const developmentResourceCatalog: ResourceCatalog = {
  skills: [
    {
      id: "employee-policy-search",
      name: "Employee Policy Search",
      description: "Find and answer questions about company HR policies.",
      category: "HR",
      version: "1.2.0",
      endpoint: "https://skills.internal.example/employee-policy-search.tar.zst",
      digest: "sha256:1d83…8d12",
      owner: "People Operations",
      permissions: 1,
      bindings: 0,
      status: "PUBLISHED",
    },
    {
      id: "document-summarization",
      name: "Document Summarization",
      description: "Summarize HR documents and reports.",
      category: "Knowledge",
      version: "2.0.1",
      endpoint: "https://skills.internal.example/document-summarization.tar.zst",
      digest: "sha256:b92f…3b06",
      owner: "Knowledge Team",
      permissions: 1,
      bindings: 0,
      status: "PUBLISHED",
    },
    {
      id: "onboarding-guidance",
      name: "Onboarding Guidance",
      description: "Guide new hires through onboarding steps and resources.",
      category: "HR",
      version: "1.1.0",
      endpoint: "https://skills.internal.example/onboarding-guidance.tar.zst",
      digest: "sha256:8aa7…011c",
      owner: "People Operations",
      permissions: 2,
      bindings: 0,
      status: "PUBLISHED",
    },
    {
      id: "data-extraction",
      name: "Data Extraction",
      description: "Extract structured data from documents and forms.",
      category: "Data",
      version: "1.3.0",
      endpoint: "https://skills.internal.example/data-extraction.tar.zst",
      digest: "sha256:f6f1…1c0d",
      owner: "Data Platform",
      permissions: 2,
      bindings: 0,
      status: "PUBLISHED",
    },
    {
      id: "citation-builder",
      name: "Citation Builder",
      description: "Create traceable citations for research findings.",
      category: "Research",
      version: "1.5.0",
      endpoint: "https://skills.internal.example/citation-builder.tar.zst",
      digest: "sha256:2c81…77f2",
      owner: "Knowledge Team",
      permissions: 1,
      bindings: 0,
      status: "PUBLISHED",
    },
    {
      id: "incident-triage",
      name: "Incident Triage",
      description: "Triage service alerts and assemble an evidence-backed incident summary.",
      category: "Operations",
      version: "2.2.0",
      endpoint: "https://skills.internal.example/incident-triage.tar.zst",
      digest: "sha256:8a20…5f02",
      owner: "Platform Operations",
      permissions: 3,
      bindings: 0,
      status: "PUBLISHED",
    },
    {
      id: "infrastructure-change-review",
      name: "Infrastructure Change Review",
      description: "Review infrastructure changes against operational safeguards.",
      category: "Operations",
      version: "1.8.0",
      endpoint: "https://skills.internal.example/infrastructure-change-review.tar.zst",
      digest: "sha256:22d4…10ac",
      owner: "Platform Operations",
      permissions: 4,
      bindings: 0,
      status: "PUBLISHED",
    },
    {
      id: "customer-conversation-summary",
      name: "Customer Conversation Summary",
      description: "Summarize customer conversations and identify the requested outcome.",
      category: "Customer Support",
      version: "1.4.0",
      endpoint: "https://skills.internal.example/customer-conversation-summary.tar.zst",
      digest: "sha256:51b9…70ee",
      owner: "Customer Experience",
      permissions: 2,
      bindings: 0,
      status: "PUBLISHED",
    },
    {
      id: "knowledge-answering",
      name: "Knowledge Answering",
      description: "Answer product questions using approved support knowledge.",
      category: "Customer Support",
      version: "2.3.0",
      endpoint: "https://skills.internal.example/knowledge-answering.tar.zst",
      digest: "sha256:64cc…c501",
      owner: "Customer Experience",
      permissions: 1,
      bindings: 0,
      status: "PUBLISHED",
    },
    {
      id: "skill-sql-query",
      name: "SQL Query",
      description: "Run governed read-only queries and return structured results.",
      category: "Data",
      version: "1.4.2",
      endpoint: "https://skills.internal.example/sql-query.tar.zst",
      digest: "sha256:9a76…12f4",
      owner: "Data Platform",
      permissions: 2,
      bindings: 0,
      status: "PUBLISHED",
    },
    {
      id: "skill-code-generation",
      name: "Code Generation",
      description: "Generate and revise code inside an approved project boundary.",
      category: "Developer Tools",
      version: "0.9.0",
      endpoint: "https://skills.internal.example/code-generation.tar.zst",
      digest: "Pending source check",
      owner: "Developer Experience",
      permissions: 4,
      bindings: 0,
      status: "DRAFT",
    },
    {
      id: "skill-web-research",
      name: "Web Research",
      description: "Collect public sources and produce citation-backed research notes.",
      category: "Research",
      version: "2.1.0",
      endpoint: "https://skills.internal.example/web-research.tar.zst",
      digest: "sha256:4bd3…88a1",
      owner: "Knowledge Team",
      permissions: 3,
      bindings: 0,
      status: "PUBLISHED",
    },
    {
      id: "helm-chart-developer",
      name: "Helm Chart Developer",
      description: "Design, review, and troubleshoot Helm charts, templates, values, and release packaging.",
      category: "Developer Tools",
      version: "1.0.0",
      endpoint: "https://skills.internal.example/helm-chart-developer.tar.zst",
      digest: "sha256:development-seed-helm",
      owner: "Platform Engineering",
      permissions: 3,
      bindings: 0,
      status: "PUBLISHED",
    },
    {
      id: "kubernetes-expert",
      name: "Kubernetes Expert",
      description: "Diagnose Kubernetes workloads and author safe manifests, controllers, and operational changes.",
      category: "Developer Tools",
      version: "1.0.0",
      endpoint: "https://skills.internal.example/kubernetes-expert.tar.zst",
      digest: "sha256:development-seed-kubernetes",
      owner: "Platform Engineering",
      permissions: 4,
      bindings: 0,
      status: "PUBLISHED",
    },
    {
      id: "ocp-expert",
      name: "OCP Expert",
      description: "Operate OpenShift clusters with expertise in Routes, Operators, SCCs, and platform-specific workflows.",
      category: "Operations",
      version: "1.0.0",
      endpoint: "https://skills.internal.example/ocp-expert.tar.zst",
      digest: "sha256:development-seed-ocp",
      owner: "Platform Engineering",
      permissions: 4,
      bindings: 0,
      status: "PUBLISHED",
    },
  ],
  mcpServers: [],
  mcpServerTemplates,
  knowledgeSources: [],
  specializations: [
    {
      id: "general-purpose",
      name: "General Purpose",
      roleLabel: "General Assistant",
      icon: "sparkles",
      description: "A flexible Agent that starts without preselected capabilities.",
      systemPrompt: "You are a focused internal assistant. Complete the user's request inside the OpenShell sandbox and explain the evidence clearly.",
      defaultSkillIds: [],
      defaultMcpServerIds: [],
      defaultKnowledgeSourceIds: [],
    },
    {
      id: "hr",
      name: "HR",
      roleLabel: "HR Specialist",
      icon: "users",
      description: "Provides support for HR policies, employee onboarding, benefits, and internal HR processes.",
      systemPrompt: "You are an HR support Agent. Answer employee questions using approved company policies and connected knowledge sources. Be clear about policy scope, protect confidential employee data, and escalate decisions that require a People Operations owner.",
      defaultSkillIds: ["employee-policy-search", "document-summarization", "onboarding-guidance"],
      defaultMcpServerIds: [],
      defaultKnowledgeSourceIds: [],
    },
    {
      id: "research-analyst",
      name: "Research Analyst",
      roleLabel: "Research Analyst",
      icon: "telescope",
      description: "Collects evidence, compares sources, and produces citation-backed research.",
      systemPrompt: "You are a research analyst. Investigate the request using approved sources, distinguish evidence from inference, cite material claims, surface uncertainty, and provide a concise decision-ready synthesis.",
      defaultSkillIds: ["skill-web-research", "citation-builder", "document-summarization"],
      defaultMcpServerIds: [],
      defaultKnowledgeSourceIds: [],
    },
    {
      id: "devops-engineer",
      name: "DevOps Engineer",
      roleLabel: "DevOps Engineer",
      icon: "settings",
      description: "Investigates operational issues and reviews infrastructure changes safely.",
      systemPrompt: "You are a DevOps engineering Agent. Diagnose from observable evidence, preserve production safety, explain operational risk, and propose reversible changes with explicit verification and rollback steps.",
      defaultSkillIds: ["incident-triage", "infrastructure-change-review", "helm-chart-developer", "kubernetes-expert", "ocp-expert"],
      defaultMcpServerIds: [],
      defaultKnowledgeSourceIds: [],
    },
    {
      id: "customer-support",
      name: "Customer Support",
      roleLabel: "Customer Support Specialist",
      icon: "headphones",
      description: "Resolves product questions using approved support knowledge and escalation paths.",
      systemPrompt: "You are a customer support Agent. Understand the customer's goal, use approved support knowledge, give precise next actions, avoid unsupported claims, and escalate account or product issues that require a human owner.",
      defaultSkillIds: ["customer-conversation-summary", "knowledge-answering"],
      defaultMcpServerIds: [],
      defaultKnowledgeSourceIds: [],
    },
    {
      id: "custom",
      name: "Custom",
      roleLabel: "Custom Agent",
      icon: "briefcase",
      description: "Define custom instructions and assemble capabilities from the available catalog.",
      systemPrompt: "",
      defaultSkillIds: [],
      defaultMcpServerIds: [],
      defaultKnowledgeSourceIds: [],
    },
  ],
};
