import type { McpServerTemplate } from "@tasklattice/contracts";

/**
 * A deliberately small, reviewed catalog. These entries are registration
 * presets, not shared MCP instances: selecting one always creates a new
 * Project-owned LiteLLM MCP Server and a Team permission binding.
 */
export const mcpServerTemplates: McpServerTemplate[] = [
  {
    id: "cloudflare-docs",
    name: "Cloudflare Documentation",
    description: "Public test server for searching current Cloudflare product and platform documentation.",
    category: "Example",
    logo: "cloudflare",
    sourceUrl: "https://github.com/cloudflare/mcp-server-cloudflare",
    transport: "http",
    endpointPlaceholder: "https://docs.mcp.cloudflare.com/mcp",
    defaultAuthType: "none",
    args: [],
  },
  {
    id: "context7-docs",
    name: "Context7 Documentation",
    description: "Public test server for resolving libraries and querying current technical documentation.",
    category: "Example",
    logo: "context7",
    sourceUrl: "https://github.com/upstash/context7",
    transport: "http",
    endpointPlaceholder: "https://mcp.context7.com/mcp",
    defaultAuthType: "none",
    args: [],
  },
  {
    id: "deepwiki",
    name: "DeepWiki Public Repositories",
    description: "Public test server for reading and asking questions about public GitHub repositories.",
    category: "Example",
    logo: "deepwiki",
    sourceUrl: "https://docs.devin.ai/work-with-devin/deepwiki-mcp",
    transport: "http",
    endpointPlaceholder: "https://mcp.deepwiki.com/mcp",
    defaultAuthType: "none",
    args: [],
  },
  {
    id: "github",
    name: "GitHub",
    description: "Work with repositories, issues, pull requests, code, and GitHub Actions.",
    category: "Developer Tools",
    logo: "github",
    sourceUrl: "https://github.com/github/github-mcp-server",
    transport: "http",
    endpointPlaceholder: "https://api.githubcopilot.com/mcp/",
    defaultAuthType: "oauth2",
    args: [],
  },
  {
    id: "atlassian",
    name: "Atlassian (Jira & Confluence)",
    description: "Search and update Jira work items, Confluence pages, and Compass resources.",
    category: "Developer Tools",
    logo: "atlassian",
    sourceUrl: "https://support.atlassian.com/atlassian-rovo-mcp-server/",
    transport: "http",
    endpointPlaceholder: "https://mcp.atlassian.com/v1/mcp/authv2",
    defaultAuthType: "oauth2",
    args: [],
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    description: "Inspect PostgreSQL schemas and run explicitly governed database queries.",
    category: "Databases",
    logo: "postgresql",
    sourceUrl: "https://registry.modelcontextprotocol.io/",
    transport: "stdio",
    command: "uvx",
    args: ["postgresql-mcp"],
    defaultAuthType: "none",
  },
  {
    id: "mysql",
    name: "MySQL",
    description: "Inspect MySQL schemas and execute queries through a Project-scoped connection.",
    category: "Databases",
    logo: "mysql",
    sourceUrl: "https://registry.modelcontextprotocol.io/",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@benborla29/mcp-server-mysql"],
    defaultAuthType: "none",
  },
  {
    id: "redis",
    name: "Redis",
    description: "Inspect and manage Redis data structures, streams, JSON, and search indexes.",
    category: "Databases",
    logo: "redis",
    sourceUrl: "https://github.com/redis/mcp-redis",
    transport: "stdio",
    command: "uvx",
    args: ["--from", "redis-mcp-server@latest", "redis-mcp-server"],
    defaultAuthType: "none",
  },
  {
    id: "slack",
    name: "Slack",
    description: "Search approved conversations and post messages to explicitly allowed channels.",
    category: "Communication",
    logo: "slack",
    sourceUrl: "https://registry.modelcontextprotocol.io/",
    transport: "http",
    endpointPlaceholder: "https://your-slack-mcp.example.com/mcp",
    defaultAuthType: "bearer_token",
    args: [],
  },
];
